spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.user=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
server.address = 192.168.1.134
server.port = 8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Turn off banner
spring.main.banner-mode = off
spring.devtools.livereload.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
