export const mockActivities = [
  {
    id: "11878631381",
    athleteId: "113249417",
    name: "Morning Hike",
    distance: 17408.5,
    averageHeartRate: 126.0,
    maxHeartRate: 168.0,
    elapsedTime: 27224,
    totalElevationGain: 1395.0,
    elevHigh: 2498.6,
    elevLow: 1364.6,
    type: "null",
    sportType: "Hike",
    startDate: "Sat Jul 13 08:43:44 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [45.624733, 24.792664],
    endLatLng: null,
    athleteCount: 0,
    map: "qanuGciivCRXjBj@nAEr@j@jDw@bCT|Cj@t@g@pAFbBl@nCrBlAHJ{@j@}Ab@Gb@Yj@y@^FJe@^JHe@NPLYNHBW\\@?w@PGIy@LOhAVFgATFBc@PHIo@j@]Zu@f@QpAdAfAoA\\wC^g@Dm@^QK@Io@PiCKqA`@gC\\w@uB?w@_@QRVSR{AZg@Ao@v@]X{CZc@Bu@z@iCp@DdAq@Bw@`@mAL??k@TAOqBpAl@FQFXIqBbAyAOs@Ja@g@k@|AkA}A}FEqBPs@q@yBBs@YYf@i@Hc@VJDY\\@@O`Af@Du@\\HAk@v@ZCk@N?AWPMRcAfBtAbBj@f@Kl@{@BNVIp@qADmC^cC]~BIzBJb@K_ATcDj@aCfAaC`EiG[CXBpAq@pFeH`@wAJsBFaGAwLOgCd@sFtBaLKiHpAeFhBkDnDoNjBoE|AeBxFcEbEu@`Kh@|Fk@~C?HKMM^q@tBaCvAiAx@qAGGp@OG[l@Cn@u@dDUjA_C`A{Al@ZrADPk@zAz@dBxBb@~Ej@rFf@rBZxCIh@rBhDlCtBPEdB~@~@|@fIk@[IZ\\@UIDHGb@b@EB]i@KA?CBRoAXwFBgClAwCbARsCOo@A]TcBeAy@}AoCc@eCFoAe@kBIkE_A_GeBiCgB}@Qh@kACq@QmCpE}CRs@r@o@BF^s@Xs@rAmA|@aAxA{AbBaK`A{CSwBm@yCDaAn@iCh@sDjC{BxB}@dB{@fCuCrLcC`FeA~ED|GqB|Kg@vFN|C@|KOlBFdCGxBk@tBqD~EgExDgDtFsAnEUvEu@dBi@Go@r@[CgCcA}@{@OfAQNDTQADh@y@W@j@YQKTBd@cAi@CT[GEZYIOb@w@l@`@BTd@KRr@nCQr@FbBd@hCv@nB}AjAd@r@KXLz@e@f@[h@BxB}A}@NtBUB?h@YNa@~CmBB_ApC?h@]b@W|Cu@^At@UPWvBn@Rz@Gf@Od@Lc@`@c@bBMbALjAQ~BLfASBQ`A[XYxC_@Rk@v@_A}@q@@Mb@UZk@XLn@WC@TUDY`AaAEFx@SBDd@W\\y@HQh@[KOh@]Ig@pAQWu@\\q@|ABj@KP}AMeCsBcDq@cAb@yBK_@_@eBF]Y@QOVaDn@{@k@kAFmBo@eBmA?qA",
    averageSpeed: 0.91,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11878118625",
    athleteId: "113249417",
    name: "Morning Trail Run",
    distance: 4906.1,
    averageHeartRate: 156.7,
    maxHeartRate: 173.0,
    elapsedTime: 2575,
    totalElevationGain: 302.0,
    elevHigh: 1378.8,
    elevLow: 1078.0,
    type: "null",
    sportType: "TrailRun",
    startDate: "Sat Jul 13 07:26:50 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [45.625526, 24.792946],
    endLatLng: null,
    athleteCount: 0,
    map: "ofnuG{jivCCDIAWFg@\\i@AcARe@Bs@UUQi@WY[{@o@m@S]Eg@AUKSCWBQDY?a@DQEUMy@DaBEmABe@VOD_An@YLq@@e@?g@Kq@CsAWYOKOGQ_@Ya@QSCGEBD@J@GCD?C@@E?BGCGE@GECBQEWHIAk@Ii@AOC_A]s@BYCc@?a@H_@CIB_@TMBqAMuAFcBQa@KW?aAHI?[Mu@GaAVCDcAl@aA|@MDU@KEYAYGa@Ca@IYLa@Hw@AeAUK?]B}@\\WBiAUKKU?K@URo@~@_@Vy@Ze@Vs@j@QVUb@GHYRa@d@[Pq@f@QVUj@a@^QBSA_@Mi@Wk@Mk@UMAI@ILCAAHACCBBO@?AEDIPGPCNBVHDF^J^?tAf@FC\\[Vq@`@c@XUVKFG\\a@r@q@HOTMTUDMn@i@r@Yl@]Za@L[NMREZAPDd@@b@PVAhA[RCT?VNPDb@?PGj@ANGNAn@JJ?~@PJ?TERMn@c@`@_@NGNOv@_@TG\\@^JLJXDH?XMd@?HBLHLBj@HL?NDT@^E^@NBJCh@@FBZBb@YLE^@^M^Aj@FZGL@`@HV?XJX@XJTAVFZKN?dAX^f@PJJ`@LHVJLANBVCl@LLALFRBHD`BCNGl@c@XG`@SVE\\@RE~@?ZDR@v@EXLTBVCBBNGH?n@Cf@Jv@Br@Nf@Z@FNJLDBBH@@FTNn@`@b@PTD`@A~@QH??B\\?JELKZMLCH@DKXOHCPFNb@",
    averageSpeed: 2.048,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11878096532",
    athleteId: "113249417",
    name: "Evening Hike",
    distance: 2277.7,
    averageHeartRate: 133.9,
    maxHeartRate: 163.0,
    elapsedTime: 2356,
    totalElevationGain: 249.0,
    elevHigh: 1374.6,
    elevLow: 1123.0,
    type: "null",
    sportType: "Hike",
    startDate: "Fri Jul 12 20:33:54 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [45.642944, 24.792723],
    endLatLng: null,
    athleteCount: 0,
    map: "ksquGoiivCDABOTQLEL@bAc@TWFMPOBMJKVMTBFADDLBZ?CHH?^D|@MTOd@I^JHFb@FNAV?\\CVMRCZHl@J`@@PDVAXGX[XO\\YFKPKFKHEH@j@a@h@Fj@XP@X?NKVGFBn@FFD`ARN@JEd@@b@EvALRE\\W@Bn@?`@QNARL@BR@ZER@ZD`@R`A?HBJETJVKH?r@TVFJF?V?CF@ZNJHJRLHJBFC?DC@BCAA@OBFRLf@AVJHV@GLGRDR?j@Hf@APBNGNMNG\\YVMFBCDDCRQPGN?HBVABCX@LEXDJHDEtAGJBRPJ@XAD@RGVAJEd@@FFLDp@AXHVN@DJ@XPdAt@LBb@Xp@VDAPB|AYF@FB?BN?NKTETSHFJOJE@EDCDABB@CN?F@?FED@HE@BGE?DMADACD?ACE@FCABEA",
    averageSpeed: 1.005,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11849189659",
    athleteId: "113249417",
    name: "Evening Workout",
    distance: 0.0,
    averageHeartRate: 168.2,
    maxHeartRate: 179.0,
    elapsedTime: 1253,
    totalElevationGain: 0.0,
    elevHigh: 0.0,
    elevLow: 0.0,
    type: "null",
    sportType: "Workout",
    startDate: "Tue Jul 09 18:17:04 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [],
    endLatLng: null,
    athleteCount: 0,
    map: "",
    averageSpeed: 0.0,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11849189397",
    athleteId: "113249417",
    name: "Afternoon Run",
    distance: 6203.5,
    averageHeartRate: 144.3,
    maxHeartRate: 185.0,
    elapsedTime: 2730,
    totalElevationGain: 0.0,
    elevHigh: 0.0,
    elevLow: 0.0,
    type: "null",
    sportType: "Run",
    startDate: "Tue Jul 09 17:31:14 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [],
    endLatLng: null,
    athleteCount: 0,
    map: "",
    averageSpeed: 2.272,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11838271095",
    athleteId: "113249417",
    name: "Afternoon Weight Training",
    distance: 0.0,
    averageHeartRate: 108.1,
    maxHeartRate: 150.0,
    elapsedTime: 7125,
    totalElevationGain: 0.0,
    elevHigh: 0.0,
    elevLow: 0.0,
    type: "null",
    sportType: "WeightTraining",
    startDate: "Mon Jul 08 15:28:05 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [],
    endLatLng: null,
    athleteCount: 0,
    map: "",
    averageSpeed: 0.0,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11838270823",
    athleteId: "113249417",
    name: "Lunch Weight Training",
    distance: 0.0,
    averageHeartRate: 104.0,
    maxHeartRate: 148.0,
    elapsedTime: 5337,
    totalElevationGain: 0.0,
    elevHigh: 0.0,
    elevLow: 0.0,
    type: "null",
    sportType: "WeightTraining",
    startDate: "Sun Jul 07 11:12:11 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [],
    endLatLng: null,
    athleteCount: 0,
    map: "",
    averageSpeed: 0.0,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11820504640",
    athleteId: "113249417",
    name: "Lunch Weight Training",
    distance: 0.0,
    averageHeartRate: 104.4,
    maxHeartRate: 151.0,
    elapsedTime: 5334,
    totalElevationGain: 0.0,
    elevHigh: 0.0,
    elevLow: 0.0,
    type: "null",
    sportType: "WeightTraining",
    startDate: "Sat Jul 06 11:49:18 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [],
    endLatLng: null,
    athleteCount: 0,
    map: "",
    averageSpeed: 0.0,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11809630302",
    athleteId: "113249417",
    name: "Evening Football (Soccer)",
    distance: 5075.9,
    averageHeartRate: 136.7,
    maxHeartRate: 183.0,
    elapsedTime: 5229,
    totalElevationGain: 0.0,
    elevHigh: 244.2,
    elevLow: 242.6,
    type: "null",
    sportType: "Soccer",
    startDate: "Thu Jul 04 20:58:35 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.071247, 23.570724],
    endLatLng: null,
    athleteCount: 0,
    map: "ghexG_tznCy@lA_Bi@_DRj@OxA?zC_@UELKLBCFD?G?BHEEB?OEMDZUFNEDHHKSGDRI@NOGH?@PEMP[H@Nk@GX@HMBFGAFBC@L@M@LGKGJL@UEDBCRTFYB?SDMBBCPLWFDAFK@KIN@@KHKAJCBBGC@EHGGBJH?ALGDK?LIIGD]RJOHAHBFBIE?EOIBLAJXGDSGPULg@Uj@?GEBF@IJN?AORMGJCUEJ@ML?YZN@JRJIY@GMENNAMIDYE@BLCVJc@HADNSHSYZF?NGBEMHDEA?FD@E_@PBCXASKGq@Fl@BENKCZU@NCGF?]JKVDH@GQEFKEK@JJ@FNACJKBMPNBDSJe@JLUDHHKAVO@CQHCPBBI?NEMGCD@CEHURHBAEWBEI?QHCFDHAHAIDDEFRSo@Rd@GMB?GMLAOJ?EE?JPENQLBYFRICSGTBE@LKBBBHKAEELDCG?@O@FQVQBUSf@BXQFHc@PEDF@\\m@CCMZGBHJOID@?LJWDZOCCKJMAJILSIFBCDAED@BKB@MNBBKBAIKJECBHLAHa@FAX\\GGIBXE[TC[J@QRB@CCDA?MD@@NHe@EHM?EHHB@VHDZc@s@VO@QIJG?FGABB@MFFCIEJCABBC?BMCHBBGMBGC@DDE@DDCKB?CHF@ABDEGEAJBKABDAEDFGK?@JDIPCDMHB?LAEWJAIPBE?BC?GCFYWLA?JJJUZNa@VHL[JDBHCFQUFE@HEUPEALGDEGWN_@IBXALEBJAC?E`@@a@FACD@GKSPNOJAILH?GIKB\\DAKSDBE@D@ESNHGDEILLEDEIL?AEQEVDCA?J?IGF@ID@GPCQJA?DEAFDEBCTD??KMW@GLHCFA`@@a@C@CKB?@PKIJAFDGFGE?PBULGU@N@IF@DCKD?CEN?QBH?E??HICB@AIBD@IC@FALDEJMELAEA@GBFEACPPSOAB?GB@DEC@BJ@EGC@F?G@BDDAQ@FODDKCJAAFH?AJMKEDLBDEECB?OFDCCEBBFADGIHDEEC@HEG@FJEGCALAEC??HEC\\IGGE?ZJJK]RAGMBn@YUDM^CGH?NQ?IDDSVEGVK]GGMv@PMCSFGHHH?NQEM]HKCAD@@VPOBFCGFAWCR?HOVEDUBHGNk@TQTv@WIEe@VNAGE@KFBBNLO@HULAONCCAYRROBS@Je@Lb@?VYo@ZN@NMRK]NANCCAFGCDIKFCTD[OBRKBKBXOABMh@GCIGL@PEPE@Zm@GPKAKBCFVGNFER]GWQGQHFTGBXFULASJCLY`@GDAGF@",
    averageSpeed: 1.014,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11807199209",
    athleteId: "113249417",
    name: "Afternoon Weight Training",
    distance: 0.0,
    averageHeartRate: 118.4,
    maxHeartRate: 165.0,
    elapsedTime: 6054,
    totalElevationGain: 0.0,
    elevHigh: 0.0,
    elevLow: 0.0,
    type: "null",
    sportType: "WeightTraining",
    startDate: "Thu Jul 04 16:21:12 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [],
    endLatLng: null,
    athleteCount: 0,
    map: "",
    averageSpeed: 0.0,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11796113196",
    athleteId: "113249417",
    name: "Morning E-Bike Ride",
    distance: 0.0,
    averageHeartRate: 119.0,
    maxHeartRate: 135.0,
    elapsedTime: 1817,
    totalElevationGain: 0.0,
    elevHigh: 94.8,
    elevLow: 94.4,
    type: "null",
    sportType: "EBikeRide",
    startDate: "Wed Jul 03 09:29:52 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [],
    endLatLng: null,
    athleteCount: 0,
    map: "",
    averageSpeed: 0.0,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11793246910",
    athleteId: "113249417",
    name: "Afternoon E-Bike Ride",
    distance: 0.0,
    averageHeartRate: 122.2,
    maxHeartRate: 149.0,
    elapsedTime: 2526,
    totalElevationGain: 0.0,
    elevHigh: 145.0,
    elevLow: 145.0,
    type: "null",
    sportType: "EBikeRide",
    startDate: "Tue Jul 02 16:36:52 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [],
    endLatLng: null,
    athleteCount: 0,
    map: "",
    averageSpeed: 0.0,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11793246747",
    athleteId: "113249417",
    name: "Evening Run",
    distance: 7633.5,
    averageHeartRate: 157.5,
    maxHeartRate: 203.0,
    elapsedTime: 3520,
    totalElevationGain: 0.0,
    elevHigh: 0.0,
    elevLow: 0.0,
    type: "null",
    sportType: "Run",
    startDate: "Mon Jul 01 18:04:22 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [],
    endLatLng: null,
    athleteCount: 0,
    map: "",
    averageSpeed: 2.169,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11769106535",
    athleteId: "113249417",
    name: "Morning Hike",
    distance: 25455.0,
    averageHeartRate: 116.0,
    maxHeartRate: 175.0,
    elapsedTime: 41702,
    totalElevationGain: 1453.0,
    elevHigh: 2513.4,
    elevLow: 1180.8,
    type: "null",
    sportType: "Hike",
    startDate: "Sat Jun 29 08:30:02 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [45.406555, 23.560883],
    endLatLng: null,
    athleteCount: 0,
    map: "}mctGovxnCsElF@`@d@VnBBDn@kG|Cw@`CnCf@zC}@lH^bIiBzCaDfDqBpNInAi@fAmEtBmBjDKbCbAdBYtHxAxCqAFTFi@dBwBbCoB~AJzGxCrCKpDyBtDgENRl@gAxAa@`@{@bFcDbTpBf@CKOt@mDxA]xMj@jOcBbI|@tAWr@f@vAWzDcBfErAdAaA\\Rf@k@Qh@C_@jDc@pB`@~@~@hCbDHnAn@k@dAbAXrA`@OZpBOrAN]hBb@`ApD~@|@lA~CJbAp@BLlAhCzEpAlAE\\f@PMfA@Nz@hAVbCIrAg@g@TMO?Fx@Dk@Dl@D_@fD[X_@j@z@bCm@h@^jBHpGsBhE?nBj@nBvBBbAv@RH|@EfBt@l@t@pBpBXhAtEDjAjAhAIdBb@hCjBxBTOpBfBr@lBzDnBHMUCRSh@?Fc@jBgAvBSr@Zz@aAEc@RIUNNGKy@XqAlBI`Ao@b@{BRGEuAbFLzAYnE}BbBx@h@fApA?Xb@JeB]MZXQ`Cn@lCvAb@b@fCPG~AdCJr@|@e@t@M\\|@EfAhB\\hBbB|AlCJvAdB\\lA`BjAFdEiBfAkA|BHzAiAfA|@pA?QNu@nJu@pBMfBi@t@?~F{@h@FxAYIBtBYACr@QUDl@c@~AZnFShBPwA[cGb@}Bh@}ANsDPVf@[MsARwEb@OHi@BwA`BgIFyCy@X_AkA_BjAkCYGZ{@H]x@o@AQr@kD`@kD}C}@sB_DiDqAQ_@`@u@yCm@PUi@Mr@K}@mBoCe@iCsBgB]gBs@i@A_@mEqA}D{CwBx@iDfEm@fEq@jAmFl@_BdB}AbDmAbAkGgAe@sBkCwAyAeBe@cCHmBu@qAe@[]`AM{AkBQ?iFgCiDSiAV]McAo@KMmAiBmBmBk@uDGeHpB_E_@Qd@gAFk@_Ai@f@sCNLm@YKRCSiBu@sAJyAwBaCSaAuByCQgAw@MoAaF}@k@WkANc@[Nk@kB_@PkAm@CkCg@w@sA{AaAHBs@aEiEuAg@R[cCHuCj@aAz@aCMoAo@sGnBuAk@{Ja@sGf@{CfA{CC}@i@_KAw@Zc@bDu@^sSqBaI`FqLlKgEJqFoC}BW{F~GiCt@cDIsC{@iCRyAeA{CIsBrAeA|Ei@j@gC`@_C[iHVuBjAgDjD}HxBuIWsBz@wDq@t@oCdGoCFc@}BYe@q@F]xCONkB",
    averageSpeed: 0.85,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11732849676",
    athleteId: "113249417",
    name: "Morning Run",
    distance: 2202.1,
    averageHeartRate: 131.7,
    maxHeartRate: 152.0,
    elapsedTime: 1107,
    totalElevationGain: 26.0,
    elevHigh: 462.2,
    elevLow: 439.0,
    type: "null",
    sportType: "Run",
    startDate: "Tue Jun 25 06:11:04 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.754738, 23.574833],
    endLatLng: null,
    athleteCount: 0,
    map: "axj|Gum{nCAGw@p@oBvAOPAVINa@d@A?Ia@QKOUEWISKq@UEYUIQEU]y@CMa@a@_@aAENEEK_@AY@@HCR@PG@BFWQgACEIaARa@LEL[TAN@VJ?i@Kq@KiBBUTSNITAd@Jb@C\\@RDBAh@BTCFBTPL^Av@G\\Cb@Gd@Ad@Dj@Er@D^C`@DO@FAHDH@\\VvB?\\U`@_@`@WJg@h@KPIVY\\i@z@G@KIYg@WiA[s@e@uAQs@Ue@Oi@OwACmAWeC?q@EKC_@Ko@?a@?EDEV@NETAPKJ?b@S^BZKzAOj@D@CADBEf@KJa@f@F`@XTFV?h@O\\E",
    averageSpeed: 2.068,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11730680253",
    athleteId: "113249417",
    name: "Evening Run",
    distance: 3163.9,
    averageHeartRate: 156.0,
    maxHeartRate: 179.0,
    elapsedTime: 1719,
    totalElevationGain: 139.0,
    elevHigh: 457.0,
    elevLow: 412.0,
    type: "null",
    sportType: "Run",
    startDate: "Mon Jun 24 19:57:50 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.75821, 23.573462],
    endLatLng: null,
    athleteCount: 0,
    map: "wmk|Gce{nCG[@a@Ca@Kq@Bi@Le@LQLKVEJMPKDMLM?MEC?GEE\\LQSVNWC@Fn@^j@~@@Dr@nAVv@F\\JdAJV?C\\YHURWTQ\\e@NKVe@JGHMp@o@JWBUBqASw@Ak@O}@CsAQ}BCgAFIPi@JKRGNMFe@HOTQLAb@OJ@ZK@E",
    averageSpeed: 1.98,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11652391604",
    athleteId: "113249417",
    name: "Evening Football (Soccer)",
    distance: 4454.8,
    averageHeartRate: 139.6,
    maxHeartRate: 180.0,
    elapsedTime: 3663,
    totalElevationGain: 0.0,
    elevHigh: 222.1,
    elevLow: 220.8,
    type: "null",
    sportType: "Soccer",
    startDate: "Fri Jun 14 20:02:16 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.07736, 23.579803],
    endLatLng: null,
    athleteCount: 0,
    map: "onfxGwl|nCTAKHFe@CJBJGALODBCRBAEHCA@ECBBME@DPKBH@IJDEE?BDCLYHJGFWBJ?KAPBBG@DIAGEDBHCOVCLQWX?FGE@U@BLI@JWNEOBEJOJ[BABLGLFECR@ECU?LIZEELEOc@BFKNF?HQBDUHB@@EGGDFGHNCINFDCDCSDM?LKAHE@W?ZKJJQGJF@DUB?AOB?CCKXOJIX@CCGLEPWCGJSD@BHC`@IBT?SPES@KD@CDJJI@?EDHG?]XB?GLTm@HCIT@DB]AVBAY`@AUPHHg@GACHAGBAGZBGCWJBIFGGHGBJJSLJa@v@_@UJKPB@M?JIGGHLOE??ELKHJAT@[MP?MDFALCGHEIRHc@PY?KDEBDAJGP@FEVAGDKAFI?MVB?KKHIE?JYCGALFN?NUVGALO@^OGCKBM?NCDP[JK@KCFCADA@KFCJW?I@FG?AJEADB?\\IGSTB?DVELFACEQ@FML?EKV_@Id@KB@EL@?[?DLB]\\N[DUQBBUDABHUJHr@@_@FG?LQh@BAGBL_@AQBSVGGJGRB?CABECXKJMERe@J?GC@VI^D@GI@W\\y@Dd@G]DAQ^GA?E_@JLAJc@AFA@?EBLGLBF?JAKHBX[KP[JLKRCBQAQCAINHMD?CE@F?GQD@VDWMCF?AJRFW\\ANUp@AQRa@HEGJECCOJ?KTWANWDWBCCRBKDRC?HFRUB@NOWj@UJFGENAIFBCODKK?MM?CGh@SF@EH@HGCGJ]T?HQN\\G[BCB\\GMDEEIC@L?CH@DAODDMIBCC??JFLDMCDAKBTCEHKAFIC?BC@@SBJCDAABFCID??DCCAM@NDEE?IQKTDFALE?RYBHC\\OLKEH?CQAJXIETWA?KF?E?ALNAELDWB?W`@?II@HITs@POOCMh@DDBLQ^AKRi@BPKXE@?GICJ?HMCQGFIABIFEBBGD?TE_@Sz@D]T[BD@GD?APG?F@?PBCCADBIi@DCL[@\\IVLF?IBAMUJAGXWd@GHCAHm@Ra@FD?HGL@NQ`@Bc@ALGBIK?KTWXCC\\ULBAEG@e@FBIVWX@TDAFc@Cg@HANPL??FO?Ud@?QHWDADVCHCA?MBKEFNNIPB?CSSf@IDCWEHFACQ@ZC?BBCB@KFJDEGJGSBHFDHQEJ@WLEANMMIFAJ@MC@D`@B?EFIKDBCBHBE?AD[q@J]Zi@NKHQXS}@bA]n@\\n@[k@La@\\m@",
    averageSpeed: 1.293,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11628851514",
    athleteId: "113249417",
    name: "Evening Run",
    distance: 5438.8,
    averageHeartRate: 158.7,
    maxHeartRate: 175.0,
    elapsedTime: 2690,
    totalElevationGain: 265.0,
    elevHigh: 462.6,
    elevLow: 409.8,
    type: "null",
    sportType: "Run",
    startDate: "Tue Jun 11 20:08:04 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.75506, 23.578156],
    endLatLng: null,
    athleteCount: 0,
    map: "azj|Gmb|nCAEBB?DC@@n@Lp@Db@GpADb@?z@NvAXvAA`@@JP~@R\\HVV`@b@`BN^R\\Bb@C`@KLg@`@MFI@IDm@r@aA\\IBi@?k@MUIa@k@QMIM_@{@YWOa@i@cAK[MQcAiBe@sAMMMPKb@Od@GFSCIJI`@Kz@ALFpA?RIjBOdA@~AAl@DLFHKOAIBm@GwABg@FSBaAFs@B{@BQ?nA]nDD`BCl@Dq@IcBNoAH{BDk@AfACj@ETEn@Gb@ATDzAC|@@?CAAGBq@GwAJ}@?]Fc@J{B?dAGn@EhAIz@B~@CfA?JGuC@SN{@LgD@bAMhAAp@Kt@FxAIx@@g@GaBJy@VeE?dAWnDB|AEx@?}@Gq@?g@RgBNkC?~@Ev@IfAG\\CTBv@C~AESBi@CyAHs@DkAPsBEfBIn@Ad@In@@bBEl@A?Fy@GoAJw@R_EBr@EXAr@K`AK`@DbBCbAA[?_ACs@\\}FAjAKxBKn@DpAAf@EVBc@AsAAWFo@@}@LkAD_A?lAIhBOfABnACz@@cAGgABa@DYRmDEaA@[R_AHKTCLOD]Rs@^f@X`@xAxC`@n@v@dBTXRb@h@b@HNHJVN^Fb@AXEhBg@`@SRU@[PY?KSk@e@aAYcA[o@[yAGe@@wAIe@UaCCu@Iu@KuBGe@@e@E_@HgAPMp@KJ?XEBCAAWL",
    averageSpeed: 2.055,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11611967829",
    athleteId: "113249417",
    name: "Morning Trail Run",
    distance: 32545.8,
    averageHeartRate: 151.0,
    maxHeartRate: 171.0,
    elapsedTime: 17346,
    totalElevationGain: 257.0,
    elevHigh: 502.8,
    elevLow: 372.4,
    type: "null",
    sportType: "TrailRun",
    startDate: "Sun Jun 09 11:43:49 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [49.44327, 11.847666],
    endLatLng: null,
    athleteCount: 0,
    map: "m{wlH{~hgARqBc@KO[@aAr@gJPmDBaCNkACo@bA_OZ}@APAS@JBMV@jAi@Zg@Bs@N]xGgIzB_B|COh@IZYjCBVTb@~AnAFz@Z`Co@|C?xDt@pFxB|@|@~DjCl@?jHdHxBvAf@Pp@QFVTRnCFvDl@\\H\\b@Lj@NPvA@rChAjCXJZFtALjUXfDh@rCnVpu@rMt`@nBtDnAjApElCrBdALYBq@Q{BgAqDY_Bl@gFfDqIhDyMdJiWv@qEfBcCr@yArBiG~BgGv@mDv@wBn@u@tCoBPkAJeH@qBQiBRw@~BP`DdAHKnAXvAGlDkAbBM~CLzBt@l@|@TfA`@nPTlBb@vA`@v@t@f@z@LrVkCxDkAlJmFnEuCjAiAdGoKrDwFl@_@^m@x@WhBGbAX`BlAvBvChB`@xLkFxA_@zGr@lEPfSStGg@pBLjA}AfAYjE^|MzBbA?fCQ`Dq@hCoArBwAxL{KlEgFrBgDbFcLzByCnDkBnKyDjHcEjQoNdIyF~CsCfAwA~@mB\\wB^mEb@cBr@yAtDaE`BcCvA_D`D{KpDsTrBeIvBoLfEaWdBuLGk@mGoMaAmCcBuDHYp@o@ZaAVwEr@aE@c@KSKR@[\\A~BaMlAoJvAwIHkGi@gIFuAE}Ai@{KWeCKqDJgC?yDKcJj@{Qb@wENeGJAV}Dj@oDLcCEu@oA}Iu@oKOkDgFc@uDBsGdCkI|DwBtBuFvIeLzJ}F|FeN~PoBtAuK~FuDhDqCbBwATaBC}Ag@qA{@uKmI_IwKsC_CaDu@oCP{Al@wA~@qBnCmBfGq@~DsB|NOlBsAhIu@vCsAxDuAxC}AtBoBrAmDbAiCDoZiHiB@kHv@wBf@wD`Bwf@pWcFz@_BPBKcR`De@KqRr@mH~ByBvAuAlB_G`KwAzA}H~FgBnBqC|DUKHVKXiBvC_DlH}BxH}ExSgGlg@qCnMkApE{@rBk@p@eB`BwHrFYDkArAq@\\e@\\eAbAuGzEoGfBcB|@eCh@yOnMcElCi@n@eCdBkBl@iDPwAh@kAFoFzAsAl@wA|Bu@h@mBEgB~@u@Wz@RbB{@nAFp@Sh@m@dBuCEiBiAg@}AyAcAzA{AzCk@TgA@aAa@aBoByAeCk@_@MDg@fAB`AKd@DfAeGfFwEtIi@xCJzFE~@sC~@y@|@eApBWjBuAdBy@fBa@lAO`BSn@{DdFw@l@s@?_@[YCGrF?\\FBIt@[x@q@bHe@tIQfJs@lHC`DF`@ZLM]",
    averageSpeed: 1.958,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11574018468",
    athleteId: "113249417",
    name: "Evening Run",
    distance: 8643.6,
    averageHeartRate: 148.7,
    maxHeartRate: 175.0,
    elapsedTime: 4140,
    totalElevationGain: 129.0,
    elevHigh: 489.2,
    elevLow: 381.2,
    type: "null",
    sportType: "Run",
    startDate: "Tue Jun 04 20:49:22 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [49.443222, 11.848251],
    endLatLng: null,
    athleteCount: 0,
    map: "c{wlHqbigAIKCBCd@@^HtA?\\Fh@An@BZ?lAW|@K`BAfBIt@C~AOhCG^MPQB_Cg@gA]s@@[Ja@Gc@Qg@IG?s@EKBGHOd@IzBWnCg@bH]|AMz@Qv@SpASlAWhCg@xCIXi@`Cq@bBe@`BS|@Eh@ITSnCg@|BKDICK@a@RQ^a@d@UTw@jAUXQG]]OC[S_A[IBM?{@Qg@AOMW?MGK?SFORCHG`@ErADlA?v@DpAATKHU@wBVc@?WHkANi@Lg@DSKSAYHy@LSFa@FeAVo@Da@Fk@E_@?mAM}@h@UZITm@hAIZGh@@v@R`CBxAGz@AfAGz@W`LEn@EvACRLNE?ADIt@Mn@IXe@~@W^g@d@e@VQFoAVMAiARU@{Bd@[LONSXYj@St@wBdROdAMTK@cA]}@_@_@SyBy@w@UcBs@KAWMCD?GGBGFU\\y@bAKFKBeAUe@[UI_@Q_@KWSMEEE?YPkAVs@Ly@Rg@He@Lg@Lm@N{AFSb@q@Tw@Qv@W^IV]vBc@pBEJCBE?EIC}@FmAC_@IYOSMKeAg@]Ig@YWUOUISEW?k@Dk@`@_Cn@cFl@iDz@kCbA{A\\Sf@s@b@g@N?l@J^?JE`@k@f@kAp@iATe@Z]j@QNQVi@v@gAXo@^}AZw@pBuDTs@Z{@`@yARe@x@gAFCA@@Cd@_@X]D[?m@De@H[Xu@`@oCPu@De@XcAVkBFUZc@\\{@JYHa@^m@b@oB?MJYHk@Lm@J_AP}@RyBLm@TcBVoAV{@PyAHSDERDVINFDH^fANdAFPCB@?BLALBAA@`AlBtBpDCPBnAAj@FRLHF@\\c@Rk@Xg@t@iAPSd@w@\\q@`@i@NMt@a@LCVB\\`@j@hALBDEb@y@X_@z@m@`@Uv@[x@e@VQZ_@j@aAJYz@kBPk@Zk@\\aA`@y@z@sBZi@x@{Bj@oAb@m@`@e@`AyB|@cBfBiEz@mB~@eCXkAn@cBHAf@F`Bf@HFBN?LGt@JGP_@FG^TnCt@rAt@j@Rt@Dh@AZGf@FPA",
    averageSpeed: 2.129,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11540299622",
    athleteId: "113249417",
    name: "Afternoon Run",
    distance: 12460.1,
    averageHeartRate: 149.8,
    maxHeartRate: 176.0,
    elapsedTime: 5944,
    totalElevationGain: 76.0,
    elevHigh: 405.2,
    elevLow: 376.8,
    type: "null",
    sportType: "Run",
    startDate: "Fri May 31 15:35:38 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [49.533424, 11.801548],
    endLatLng: null,
    athleteCount: 0,
    map: "{nimHs~_gA?IKo@Gw@o@uAKk@Cc@BS^W`A_AR?Fa@rAmCfBeCr@s@j@[t@QR@zAa@jC}@v@]RU`@[`@LAOIQ?Or@}@\\s@r@sBh@_C@MCKAKFi@@u@Hu@^_LAaBD[Ta@h@Tz@L`CLnANpBAdAFrAEnCOx@IhE}@dFuAzBaAX?nAQl@g@r@[jAQhAa@zA[~Di@v@?`BMdCHd@EbAF`FD~APp@@~CQ|@WrCa@pA_@xCmAfA]bCsAtAg@zBkAhBmApAgBjA_Aj@]jAe@lAUlC}AhCeBp@_@jD{BxBeBJMbAw@D?XUf@WZ_@Zu@NMn@Sv@e@^GD??B@GJGIN?RDDFd@Fj@CzED~@BF?^HnABt@DPJFdAc@rAOxFEbAE`AM~Bg@vAk@`AWz@k@~@OXH`@\\lDvETLd@@^UtDgF^Y\\@x@|@n@Tb@Ed@Qf@]v@_@n@SXAnBPb@LJE^Dr@TPAb@MHIDORgCBu@Ls@FU\\m@Za@`@Af@Kh@Vx@D|A`@j@AJE\\PNZDZInAHzBh@vATb@D@JZDj@FJD@lCsE^c@VKVUP[tAqBtAuAvAgAz@}@lAeA`@YlAsAHCz@q@vBoBV]h@a@hDyExD}G`A_BTk@Ze@x@aBb@a@x@Op@[XHHAZi@RQrA[dEANGn@@|AMzAB~BMvA@x@EtA]tCgAx@_@`B]^Fl@Ez@FHHP\\RA`@w@fCeDf@i@`@o@DGG[?OLa@h@a@jAgB|AqBdA_BzC}Dv@mA`CgDd@q@Te@t@eAlBaCzAcBRY`H_Ij@w@p@u@xAkB\\]j@u@\\Y^a@~@oAt@o@^c@NYnAaBxA{AhB}AfCsAZGn@W|@QdA]jAIjAUlBEbD[dAW\\Wr@q@n@u@|@oBFe@Pm@L{@B_@@w@Hs@J}ARUb@kCZaAl@{Al@iA^c@z@{@tAcAz@]|@Wx@a@r@QNIAi@B[DWHGxEiAt@JhGkBn@I`Du@j@Eb@\\PBj@KFGP@XPFZp@dDJr@Bj@R\\FRRrAJXRnALRZLh@l@P@h@Pn@\\HFHVJHz@TjARl@d@r@VJNDACARAh@JbBEpADNNRBHFBF?t@VFA@@FNAC@",
    averageSpeed: 2.097,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11526557066",
    athleteId: "113249417",
    name: "Afternoon Run",
    distance: 5113.6,
    averageHeartRate: 132.6,
    maxHeartRate: 146.0,
    elapsedTime: 2702,
    totalElevationGain: 38.0,
    elevHigh: 408.4,
    elevLow: 382.0,
    type: "null",
    sportType: "Run",
    startDate: "Wed May 29 18:21:20 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [49.533108, 11.80034],
    endLatLng: null,
    athleteCount: 0,
    map: "{limHcw_gAAXHl@HRLt@Vp@Jj@@b@Nx@Ap@k@hAQVYVi@\\qAj@GFMRI`@[|@_@l@Sj@Y`@[x@_@|AOlAId@Od@EZEdC?p@HnB?l@YnBSdAEtBDjBL~B@xADDBV@ZRnBBdBH^JbB@pAC`AGv@Gh@YhAGf@i@rLGdCCPGBe@Du@LQJSZi@bBSx@IBa@Ck@HUHK@KIIQa@kCe@mCOg@cAcGWmAWgBQwBSqG@u@_@yIA}AEMEICAK?}CfBc@\\e@TQRo@Zi@b@iAr@MJ{BxAEFEX?fGC~@@hHEzA@|D?nDCdAFf@`@zAN`@b@fB{@wD[_AE_@DgCAiA@gFFu@CaB@mB@{LPWNIROLCf@_@b@WVU~@i@NYNKjBgAPObAm@r@g@`@WLEDGjBe@x@KpAWNAxA_@d@Eb@I`AURSHUJi@D_A@WEiA@sBDsBDq@?u@Dw@JOz@Kn@QTQNWNe@b@cDJc@Vq@^u@HWHIJ]~@yBV_@HEr@]TEXURK`@_@n@iADa@A[Oq@Ge@I[",
    averageSpeed: 1.952,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11487636989",
    athleteId: "113249417",
    name: "Evening Football (Soccer)",
    distance: 5065.6,
    averageHeartRate: 151.2,
    maxHeartRate: 190.0,
    elapsedTime: 4271,
    totalElevationGain: 0.0,
    elevHigh: 222.6,
    elevLow: 221.6,
    type: "null",
    sportType: "Soccer",
    startDate: "Fri May 24 18:49:57 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.07748, 23.5796],
    endLatLng: null,
    athleteCount: 0,
    map: "eofxGok|nCF@UBH@AFBECFOITPFKE?J@M@ADHADME@BFC?@HBCEMQJGCDEAFDC@FE??ERQADFBEDAGAHFKHHWIN@ODFCIAJCCFFC@LISJDO?KTHg@HCKB@N?MHE?KIBDDOR@TAYRM?HIALMAJD?Kn@Dc@ALAKDQCFHBGLBII@CHDGFHIADG@JLQQB@LEGBEG?PBIBGGLD@HIQBCE?FNMEBI@HAILIPa@CZEMAFDFEKBLEGDOJSFBALEGARGDOQ?JNC?LHO?P@UNA?KW?GV?M@LN]BZO\\[XGCVc@CKNOEUJNAHMCBD]b@DF@f@?_@JW?HBAELQENSD@CMH_@XQMb@OLASFVLURCIHDJq@t@E?T_@F[I@NB?IGKDQDFE`@YADKEEB?c@n@NGVk@PFEMSZP??LGFLS?KIYTMDXIf@_@KFQFABDGBCJVGGHNYAFCSF?KZMNPe@FF_@p@E?JKE??MVa@IBIV@TEGOC@J^MIIAHBONE?L@_@I^OPBUALBE?JGRIKFABDKGT?MGNDHg@Q^AOLGG\\S?Za@APF?GBEMBKG^WNH]RI?PFQGA@IDJKX[H?DHGPa@@QTKCVOJ?HCICJ@KCPP?EGAQQ^GSHBL_@?PKFEb@GDEYIJFDABJEFk@FECIFj@WRCMKDZUDOCUGXFBEKFFHSCIK^B^EAVe@GTI@ALURKIDS^k@HAAHH?SPDDKJ?HPc@LKEZKSHGHDQNJ[LFSXCMFDAQAFV_@OHGZMDJ]@JRADIEGQR@ZYf@I@X}@Ze@AJ@KL@ANCCB@INKAD@DUFCKDJAKBDNAMGDDHEIDBIHH@EIADB@EKF?EDBLGIFSNBKKAHFHKBPOIE?PFAAGMF@KEVMRAFBE?NEIIPOAFEAJEMRGAXHCGCCITe@Wx@GKJWLNW\\CAB{@CBELHAPUE@BBDS?LARMEZKY\\f@s@CP[\\ERACNDMDFW?NCBJc@[THDFOOAHLATHCEKNk@EGJDEHTD?YQDDRIKEREENDAGGEASLBc@j@JDWNNi@PEUABMCR@TNE@DK\\EYFIHBQLY@B?@SLLJIDYOb@BD`@cAI^LHEOGFFC?JWj@HWLIQEEDJc@@JCCDBHOE?ALIGDD@_@JER`@G?_@z@KA]QLS?H`@MFMI@FCESIp@?GBA@LARDi@HEBBOb@MA?FG_@JHRAMDEKFOBB@SEE@JOz@KIFi@EFBIJA@MA`@KFHUCTICROHc@JMFPF?QDLNWABJo@b@PF@J",
    averageSpeed: 1.231,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11464395310",
    athleteId: "113249417",
    name: "Night Football (Soccer)",
    distance: 4690.3,
    averageHeartRate: 134.7,
    maxHeartRate: 175.0,
    elapsedTime: 3934,
    totalElevationGain: 0.0,
    elevHigh: 331.4,
    elevLow: 329.3,
    type: "null",
    sportType: "Soccer",
    startDate: "Mon May 20 21:04:46 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.770084, 23.634169],
    endLatLng: null,
    athleteCount: 0,
    map: "_xm|Go`goCHOCD?HCA@ICOCAGJ@JJ??KC?BK?BKHFA?IHGCBEO@RFDIWC@DTCIB@HWALBGC??IJCe@f@AAXQDEACD?CFKLEK`@_@ITQHF[VQ@P]d@DQAFMSL@BHCZ@EECGDLIR@?EKJI?AMBE`@KIDCJNH?GFEIHWBOLEC@GRUW^ALDME?PO?GD?G?EJG?^UFOFTEI?JE?DB?Bi@?GFGMZCFR?OQCNEBJCKELFMIPNQFDIAORMBKMPNCONSNC_@\\@BNEH[R?_@NQEDPALHQ@JKEHB?FMHp@i@KRMLEAF@CIKJIIN[AGLDGGMBVIGHBFEH?GLEL[BDQh@UNAPEWBKNOFOF?CVEQO\\?EF?@E?JBCPa@AIC@HGIh@FZL_@k@b@XUKAWFLG?DDCBFUFEK@EB@BJITLUJGAABGGBF?AJLKK?D?IXINEE@SK?IICBNKPN@IIKDD?MEDF?BW?JB?LQUZNX?y@Cb@HGAIQABFEPQRBGCPCUD?BFCB@ICHG?DDEGADJECAAHAGC?FH@EEB?GCHF@CEJSPGCKC@MPJD`@SQ?SNBJGDV[KHDLCIMLCA@G^[DMCAJHAMF@MRMDD?GI@HJFMICULEE?E\\FFBHPMKNDYYX?HDIB]@JPLGCDOEGMJMRH?AICFD@]CCEF?BHDK@FPEAa@FCB?IPHKACCFDAIVa@TTm@JGNN?JK@QPECAFFo@EFH@JLGAEPIABEHEV?YRE?DCCCKT@O@DBIFC@NMYFKD?ANIHDIEGSRACDKHF@LBMRIJ]KRFBDT[JL]GKDHCDWDAKLHCDDMFCEEKd@d@}@?QKQNTKb@IJJS@HCHDGOCKJFA?NG@?EFIIJM?DHZYMNBBBEEF@JB?CA@?AIBMLGONQb@AHTc@ADMM?FBIFAFXLIHS?NGEGHHOG?DECAFFGCEDDB]HFELAG??E[PHJGM?NBFA[HQIDCVJQMH@FKKVGKF@RF[EFCFV]@F?CECINPILM?CBHFEi@b@ECR[ULF?f@]DDBZg@HCMELJYPBG@DA?UGTNODA?DKLEAGKI@JGZEIAELWRDBGGM?D@Xa@@P@E[^AEO@HAJON?OLFDCC?KP?EFM?FBKLHDFIDi@DJDGSLMb@ECEQFCFRNB@]DN[H@HCFHMKIEA`@ATSQe@A^U\\FMILCCXG?FRYACMTDNDSGKQVSD?GHOPA?CC@B@FGCYBEGRSF?XBB?EG?@DKLJ[IGANIJBB",
    averageSpeed: 1.24,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11414714215",
    athleteId: "113249417",
    name: "Evening Football (Soccer)",
    distance: 4142.9,
    averageHeartRate: 144.7,
    maxHeartRate: 186.0,
    elapsedTime: 3371,
    totalElevationGain: 0.0,
    elevHigh: 332.0,
    elevLow: 329.6,
    type: "null",
    sportType: "Soccer",
    startDate: "Tue May 14 20:04:11 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.770084, 23.63474],
    endLatLng: null,
    athleteCount: 0,
    map: "_xm|GcdgoCCBDLI@BAAC?D]ZCCCSHA?GHn@BGEKBAE@DCBKBLBIDBCDGKDGK?FEFJN?APGEBADIEMANFFLI@GUD@K@HLIIB?DSN?IOB?DEGFBCc@C?EJHPA?JLMC@CLSE@@?EFh@w@EG@NGP?NSFBJJABDQBCKFH@IEADC?QDDTI?FCFEa@SZ@JCECPEDJEXi@GBEC@ADABFJBGHEGGB?DNEBFAHCE?G?FGGGPML@DIIXEMD?OHDBCQ@DHNEDMCMFEOP?HGFC@MSIT?HDGCQKFBEJDLe@R?I?@MBJEVBFGJECEB@QMDFHDICDB@JO@@AAELB@GNLEFI[DV?TS?BGCe@XD?EHEE?FBH@KEEJGO?BQDALXNC?QEFFa@@D[d@AFD?CQ@GRa@?N?EEDEEZd@EOM?FGD@AIILAKI@?DKH@B\\BFHEGIDFQKBNc@YTCJIIFNEEEFF[GP@DBID?B[OA?DH@M^EEH?AKA??ZBBLI?C?DWHDHF@AENc@GH@D@EOACFDNDIZGFG@ICSEBAJFLU?HTCIC?FKI?CHB?EANi@LBQNGJ?JK@GN@FLGCDDYGCMFFXNIIA?K\\[@GAHI?EABCC@ETXQF@?HS?CFOB?TEAHGCEARAMEBDC@DA??EEC@EEBFAAEEDDKDPAGNGMBKLA^BCAEDO?MJBGAAEC@NMILIAHTDGE@TGUACDF@d@UUAGHJMH]CIIGCDBBN?@TAF]VWECGADBB?GRHDA?H?CLA@EE?MBEHPg@APGCH@?`@D?K?CGH[DFADEAADAGKHB?De@RYET@BEAANKNAAD@CFH@CGE@BE@@EJDQL@E?@FS@KQADFIFDA@B?E?B??DM\\@BV[EA?DBC?DG@LJIOPQMFLCKL@BNg@SJLFEOCBV?Ib@EEBKMHCJBAM?HSMDNGHBGYICEFAVRKJFCHSHELL[I?MH?C\\BTO@EAIOVKDAEWAVI@IAHK?KDFDHIKJPM?CCDG[Cb@JIPc@CF@NCTINFAEALK?OKXH?EGAMABRLBKKGID?HEFXi@?NQPCGGVL[AGAJ?ID@BJCECFKHJ[GPHDCLKCABF[HC?F?GAHBEGCCH@BNBNAPQ_@FYVHOj@[[T?FHCDOE??GEPE@?u@@DS^B??HHEHMBa@ECHN?DKRC@CLAUIEFEBJALGEEDFCLWCGABMb@DFKJRMRQq@`@@@^g@@DBCGPMHR@OEKTBH@[BC",
    averageSpeed: 1.293,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11348072588",
    athleteId: "113249417",
    name: "Evening Football (Soccer)",
    distance: 5486.5,
    averageHeartRate: 146.7,
    maxHeartRate: 189.0,
    elapsedTime: 4510,
    totalElevationGain: 0.0,
    elevHigh: 222.3,
    elevLow: 220.8,
    type: "null",
    sportType: "Soccer",
    startDate: "Mon May 06 20:50:14 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.0774, 23.579706],
    endLatLng: null,
    athleteCount: 0,
    map: "wnfxGcl|nCAKPc@VMW`@BDICFHCHAEVk@MDM~@_@\\P_@EGFEGALLKWGJK`@Nd@Dk@QLTUDBEBLAo@JEIh@GDSGLBb@CRBEKEBUEMNWF^GEQRT_@DLGNKKHM@X[FH]^g@B??X@[BN\\U[VCEGJ?[BDHIATITSH@HEENGF{@GJBNKJDFELAGLIAQR@FQEI@NUDMh@NMEEEFAKLB?HBKKRJa@HHURBPSIF?CN@[JOG?XYIJHJ]r@IBHg@G?FNB]HDRIOXIWOAGLCVF?Pc@EN@TR]KIBSD?I@DLFOI^KDVOGRM_@HE@QO`@NEDHCUEAAZ?MEJDa@AVLYAj@Lg@Cd@GJO?OVWM^GOGp@u@ERWJNK?OCh@CMDWNBCEIb@AMJBHUUX@HAQFFEE@LDGDWHE@JQ@?LLMECLASHO`@ASFGG??KCNC@?SDAKf@HC@SEL\\YCJCKLMERI@@AFTSRGR?e@JE@UN@GFUDOn@HBEQBYFM?FFADg@JEI@BPESDAGD?LUx@[@BEN@MLLI?HNk@JO?MHEAHMECJJDAVGIUALKLNCFIQJCBMFF?REPEGR[@PQ`@GE?JCe@M\\Cd@FIDe@L?IROSN]ILCG`@WK\\IKXWE\\WXD[NIPGDHO`@g@b@Zo@Sd@KBJ]H@OFGd@DDLm@A_@IELUF@Eb@IE?IXQDHa@X^u@MDK\\Mb@FS@TA_@E?Cj@DHRi@@HHFMQL_@LDC\\MHF[CLAQLYBJDEQLALMIFWX@BLMXEACNG[HAQNEZD@@WK@KNJIA[DCXAK^@OV?WC@R?GK@OPJGI?HC@UQVR]ALFGAOTYGBi@t@ENH@IFHNKSNK`@w@?J?OHACKG@@\\G@DGCGC\\?SBBALIPG@NW@Q?JIF@LFOMHX@EIYLARESFPDODT@IGLB?GSBKB@Gb@IC@JIBj@gAEB@LBABYO?GZJZ@IF?e@PJ??ME@FA@KDTIFP{@JEBNG?AVBq@G?Cn@IPIA@MTQ?QIRDFGMGFT[@FQ\\Fe@LIGJJF?J?YGAFKOj@KJAKUn@JKAIL@UVV]LEG_@DKED@b@PS@Kc@l@KF@QHFAVJ{@M?ARJBDSHJLQKOBID@AE@FLEONBQPJUX?MEDDBFKCILAGEAPIAHGEILFQLDBAWD@?JDGGCH@MJLAKDBBEKJKKJATe@rAIB_@g@AK^w@j@m@?c@",
    averageSpeed: 1.253,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11339967985",
    athleteId: "113249417",
    name: "Evening Run",
    distance: 4718.4,
    averageHeartRate: 151.1,
    maxHeartRate: 187.0,
    elapsedTime: 2169,
    totalElevationGain: 11.0,
    elevHigh: 243.2,
    elevLow: 239.6,
    type: "null",
    sportType: "Run",
    startDate: "Sun May 05 18:07:15 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.07861, 23.565832],
    endLatLng: null,
    athleteCount: 0,
    map: "ivfxGmuynCGe@A[@CT?JCTOJQNa@Dc@Ao@Qk@MOMKSEi@?e@EiAC]@KB[TSXKf@AZB^Ld@PXRNNDdDLH?RI\\]N_@Fi@A{@IWSWQKOEcAEwAK_@BWLMRSl@Gf@@ZNt@V^PFlBB~@HZGPKPURu@Do@Ge@GUMQ]OiBIiAKK@WFUTOVKh@ANBb@Jd@LZRRHDNDpBBp@FZILIJQTk@Di@?YKo@[c@KEWEgACsAKO@MB[VQZIb@?b@B\\Jf@X^TL`DLN?VGXWPc@D]@u@Oo@Y_@KEUEu@CyAM_@?SFUPKNK\\CV@h@Lz@LTTTVD~CHR?TKV]L]Fi@?a@EWKWQWWOw@C{BOI@WFMHGFQ^CNCb@Bb@Jh@N\\RRXFPAjCJ^GDCVYPg@Hq@?WKe@[a@c@QeDMK?WJYVKVI`@Ad@Jl@R^VVh@LtA@n@FNARETQHQNa@Fy@Ag@GUQWOKUG_AAYEqAGS@MFSRO\\KXCf@Hd@L`@T\\VLzBFb@FL?PETOXe@Ja@@o@C[K_@UWQKUEe@AcAIYAk@?WJSTO\\Gh@@l@Rp@JPPNVFhDHPCVMHKL_@P{@Ck@EQO[MKa@MoAEcBKIBWLQPKRIh@Af@Lt@^h@XJ\\Cf@@bAFLD",
    averageSpeed: 2.184,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11317528981",
    athleteId: "113249417",
    name: "Afternoon Football (Soccer)",
    distance: 4448.6,
    averageHeartRate: 161.3,
    maxHeartRate: 196.0,
    elapsedTime: 3869,
    totalElevationGain: 0.0,
    elevHigh: 222.5,
    elevLow: 221.3,
    type: "null",
    sportType: "Soccer",
    startDate: "Thu May 02 17:59:13 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.077526, 23.579699],
    endLatLng: null,
    athleteCount: 0,
    map: "oofxGal|nCFG@LHYJETFEBId@IKEFDEICDDDM?WL@FQBBNKKAHHKBBDEDASF@AKF?ARE@KAP?OKDEEBJ?@DBAGG@DE?LEGADLGEEDHBIQJLKKFECJ@HEADFGK?JJCM?@HFFJYQDH?BIGGLLOCBLGHE@LIGQBM?FHJGEDCAFIB@JF?C@?GAD?YJNK?DEIHAGBHEBCKBGDRBQJAI@AFEEFQIPJ@EOBEGd@E?ALDEN[B@CEa@`A@KMRG@?ELOKV@MVc@D?Kn@KBJq@@R]TDDHKDYDH?CFGRCCHMJIC@JCE?JGIH@DECAJCBE?MIFEIQN@Cn@[IBK^EQGHQABBFU`@SKLI`@GBEa@H@E?BDLO?JGOHK@^e@d@?NDEAG\\[MAFSP@i@R@NBMFAJk@SZJODDBLITDDCIG@?FV}@IFJEER?\\CAHBWHOTEG@KHQPKEIDJO\\BUFGBDFO?O@@FVOT@FID?DYDHD@JDm@CCEPDACMBA?INSGB@PDDPIHO?HEHG@Pg@K?@IEPUV?HNIJc@JAWt@MJLW?KHEII@GIXBAUj@CADBAHHy@CAEJDNDOPI@IGDFRU@BM@H@ACE@JLKCTECBKBHBE@U]v@MBCKP[HC@DCBF?Ob@YGJO?OD@E?FDEIJTCCB@ELI[h@w@BVJNM@PCGDCWW\\BHCMH@ANASBG?JHGe@fAKHBa@JFIKIB`@c@C@EWDTMZLGEHIAFACSJ[R[FB@VM?HMIOD@ANEF@HE?F[FHCXGABDGB?G@@GRD@DIKHIGFFRGWDB[D@C?COGr@GN@FLAEGMBGGDADTCQDOXG?KJQPE_@j@A]a@BAJDDX@Hc@HGEL@DEA?_@EG?FDCHVCIC@Il@Ro@@BUp@B@@WHOD?Gd@ONC[BQE?J?MLHLBIURD??ODCEANO?MDAIb@PKAHKNBi@QNH@Lw@DHWp@GHAEEXJJUAVOF_@IEBCCNCEJQEf@?WFB@J_@`@JDAWO@@HH?ATC_@HMDCBBALFYASB`@ODKPAON]AFC@BKHEBFSl@CEBG@l@EEBICYN]LBGEBK?Ta@`@PYPC@HCSE@HHHGYj@G_@LKMr@DOBe@JGIDFEEJIEAJ@YIb@IJ@?M@CEPKLHB_@FIFCHFHCAZCBAWIBDe@B?AFOC@@?VI@?XAEHGAGE@DEn@SDDYR?FIW@ONEAVS`@I^ON@HGFGABCAEIFHE?F",
    averageSpeed: 1.19,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11299678821",
    athleteId: "113249417",
    name: "Afternoon Football (Soccer)",
    distance: 4880.2,
    averageHeartRate: 166.1,
    maxHeartRate: 199.0,
    elapsedTime: 3643,
    totalElevationGain: 0.0,
    elevHigh: 222.4,
    elevLow: 221.3,
    type: "null",
    sportType: "Soccer",
    startDate: "Tue Apr 30 17:58:49 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.07735, 23.579536],
    endLatLng: null,
    athleteCount: 0,
    map: "mnfxGak|nCK]DAADD@EI?HG@APKLFCAUBFAEXYMPAh@GHB?CMAL?QXS?GIBGc@C?NLA`@EB@BEABIG?HGYTLUJa@CFFA@FCJEA@LEIHBCFDC?QFJMICBDC?H@A@ICADMJD@OBRMHAFNMECDEQDFGC@?SHKIE?XDWITD?Pi@Ul@DFHGMOFK?M@ZOXHA\\[MEOZCJJN@GEAM[Iv@?\\IGRs@\\g@F@@DEIBGJDIZGDGGAVQGNo@HCMLHBIRBJU?BEJAIDMVZs@AOG?F^EFACJM?MECDFCNHKEHB@NYELBCBJISGNJSFBKHDEOY?I@HNNGHBBEAFECEFDIK?NDEEFAEDJCKGRBINCAMGGEHFDG?BAEQ?NDHEB@IBDCGBFEJFECCHEI?Q^@WBDDGIQFLEPIJDWREKHBH?OFBALKBEJV[SBH@g@f@HFADIEFGSBIMPD`@y@ID?IE`@DLPk@AIGAGZ@BPQ?EQb@?KJAH]DF?NO\\IITBB[CD?KM@?M?\\Uh@CXASHSBYEVAIEHATTg@GBG?FC?PESLNH??FAe@NFGJ?HAKCFIGRG@GW@W`AOIAMBEBVJa@JAMRDIAEJOHAIBBZGVIc@F?EMJLGXIIHBDUCSDL@MBAEh@BBGMBJQJOGj@u@HQANDEAFD?CJKLIEASBKFNGNDAH]AJ?ED@I\\OGP_@?IHGCl@?KECYbA@YHEDULHIJMDM`@Tw@Tk@B?Ah@EDME?GFHFOF?EDGICHE@G\\EI@Ed@a@Yr@KY@MFJMLBDGGDDd@c@SZ@[BC@FEJBQDEI^PG]JZUCNOLFIB?AFBGEHJCG[U?CPJJ?JIP]PFWZ_@EC@QDAA\\Ea@?TSFBPCDJ@DJCDF]CFOKVIAQBKR?CTSGJACCV]AVGQL@Qd@c@v@Vq@FNF@UHKPIEFYTq@GBJHQn@Dc@JDGCBS?TF]FFCNEBKKI@YdA?MLU@KLSFAJSDACRHYDLD??FOO?TGQD@FGALGLSJCGBFMLFTOPEGCOBKRGFURGFKCJMCHNg@r@E?@OLCCODMCACJJUPE@FYh@@PQQBR@_@J[TMC@DREHAKG@?MFRISBLRw@CLIH\\BGM?ZKPCCAJCEEFDULI?EU`@CO\\a@@LDBIGBHITKEDHOHGRFe@R?Bc@?HC@Ih@C?DWNAISDABB[AGPTDJ]IDLLBGELE@g@b@MZIUBCHQLGFH?LG@@SLQHFKJGCUV?RJi@NICAEh@Fm@JC?NW^JKLIN[@Q",
    averageSpeed: 1.359,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11299679035",
    athleteId: "113249417",
    name: "Night Football (Soccer)",
    distance: 5293.2,
    averageHeartRate: 150.3,
    maxHeartRate: 199.0,
    elapsedTime: 4178,
    totalElevationGain: 0.0,
    elevHigh: 222.4,
    elevLow: 221.3,
    type: "null",
    sportType: "Soccer",
    startDate: "Mon Apr 29 21:02:16 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.07736, 23.579704],
    endLatLng: null,
    athleteCount: 0,
    map: "mnfxGcl|nCHCAJOJXa@Du@O@@d@MDFB@KIl@F}@DTIBHACEELFB?E?FBQCMIDFAEFBRAYK?B`@?SDAGLA`@Bi@BBM@BULJAMGJBHBEKEAXFIDNKSF@@LI@@SLIJYINC\\SQBTAGh@[EIGCCDNBWAANNCJMMFFDCIMN?LH]HHo@nAPYBDGEHKBWRW?IKE?GE\\FFCFG?HUGKGFCJBEDNJCNWCKDHCTORBABFENDYEWHBKDIRAFJC@HGACWG@N?MDBDGYQz@LFVUEMGBFKKGN_@IVFCBKEIFA?K?NHEM@HJ@Rs@r@?GRODWCJH@@SCBHE@HSb@Jo@CZLE@WCC@Fo@`ALFLeAB?ERFSAVBCAMS~@Q[TWFBKAHd@Fk@DI@FMGNMAOR@AFDL@OORQIRABKHAO@E\\EKJ?AIJE@IBB]VCNLN?FWR?J?_AH?DYDBGPCKGB@TDDRSA`@MFF?@]REGA@YMJJP?YGKGBJDMT@VEUICFLN@GGA[Kl@NK?KE@IRGBAHNSO`@B]E@NWEAPQ@RMLZWIAOTATNMTo@Sh@BGGGOFYt@DDTa@Nu@?IGAKLA^KNXZUJKWBMCA^_@?FCMULDRGf@FFCJBWDBOm@JBDIFYEEIRH@AJH_@HBGFBFC@AIHKYr@X]P]GBKK@N?GSn@KJGTGAHEJ[GGVc@^QAXBAGKDNEDPAS?FEIJEMADHDDQD?CD?IFDECKJDKH?O@L?DFKOCREBTBOAHOCF@UCFHBMCF??HIILBMJ?]D^BEIM?HHD@GCKGRDIAGDD?HKTFBQRIKJUHDGT@[CF@LCMFk@HBMf@KHPBGW_@z@GOIFZU^u@YBBLHMKn@MPAXE?@PEWC?DWXGKRDEEKAWDO?FD?GAHG?X[h@APDJCOF@E@DCAOQATIJg@RU^Ag@|@EGFI?FKADQAPJK?H]b@DCEIZOHw@KND`@Q^QLRu@F?EA?ECBBDGENMACCNBDHWEO_@~@BDEMFSJGOTRUAc@DCHAEJK^KJMIV_@E?Ur@BIFLJISNHTMSDMKXGGZa@h@_@[?DRITBVGSDBFk@FIDH[t@CKIBEPBIKA@GCLXNCIL_@AND?@o@DKGBNWg@z@AXLG@]FJEBFKCEGf@B[HICF@FGVGLM?Ro@@GEA@\\DGEEDAEEVIDGEVSVMKRURGOPPBSBGLLOEE@U@HF@DEAUVDDIQVSJPCBKAYMBBJJBS\\JFHe@H@DFSRKIAL_@b@@ZBAGJGEDC?B?ICJ",
    averageSpeed: 1.324,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11286792125",
    athleteId: "113249417",
    name: "Night Football (Soccer)",
    distance: 5069.7,
    averageHeartRate: 155.6,
    maxHeartRate: 197.0,
    elapsedTime: 3699,
    totalElevationGain: 0.0,
    elevHigh: 222.3,
    elevLow: 221.2,
    type: "null",
    sportType: "Soccer",
    startDate: "Sun Apr 28 21:02:30 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.07732, 23.57974],
    endLatLng: null,
    athleteCount: 0,
    map: "gnfxGkl|nCHHIE?SLNAGBDAEAHIMBBFe@HJCFMD@C@LKZAKK?FNBG@KDECDCe@BCABB@?TDYILLCEC@EEREA?EBPI^DGM?HM@QMHH@?ED?JQPEIBB?Ec@M^AVIFPYSRDFCHDEK@Vs@PJDCKIEBGLNAEKMl@@KGJBBEGLECa@FBGHNDGFJEADIEC_@ELBFEGC^?ERWCPF?UTGAHKJBJC?QEIKDCVC[ATSJLG[l@RE@ECGNEAKVM?EKFELYCP@GD?QHUBXGXMNHOEQPQ?IEEERACATRc@FHEND?He@AXIFCODM?XCOId@D@HUIQCDDZKP?LEHFw@Ze@CDHTUH?WC?O`@`@[BIO?KPJA?MGAKb@SJDZJu@EB@PIPXe@D@M@D@HWFHGFAODBEXMRd@s@IAYb@@FJ[KH?DD@UjAGBJo@RSDFENQHJCHs@BFFYAG@h@I@Un@OBTg@?UBKCEDHKCF@?XMJReAQh@?GFBLI]bACA\\w@D`@GD@KBABOI?JIICERMN@KDPHFKFG_@JLJ@Rs@Yp@OFEGEHFEHP?MNY@@I?@IUXATDDR_@Ub@HCIK@KXk@LMI@APCMBDQV@SICJ?DJFKE?D@UZQ@F\\Jk@L]HDK\\PUDSW@@PCF@FDCHWUFBGVIIICl@CB?WUX?d@UGHKJc@JACAIf@MB?FM@b@_AXEFIM`@CKKJF?KO?\\MZAPBQHEJc@NSEACLDKMGAn@Wb@Ra@D_@DJG@FCAEN?KL?HAGWZOJGAVk@VY@KARH?OECBM\\B`@I?l@{@JCMBELD@LO?GIEB@MFKRB?Bc@Qr@?TDE@SKV@HGAFADUHE?MBBMVCZCHKCAUIENQ?M@BCFBFH@G@DBD[HGE?BFGA?ILECIGPBJXDCBAMGCCHDIECLML?AASb@GCDUYb@DK?HDCD[FR@EI@Yf@MEXSF?Jo@DTQ\\XEAE@DCQFWMH?NQFATLB?OGHYHFIA[DHHAIGEMARFBALDQd@YBEEQM\\Cp@MD?JEJ?o@DDSd@FCHWPw@LADFKJUl@AQFE?LKETA]b@CGJ?MEBHAKDS?JPc@KHXEST?Y@GF@CQD?GXLYMESd@l@c@EK?V]|@AIDK?SHS@HEJQGd@a@OZIC`@WANKHGTUNGVASDYCICf@BJENBOXYSd@GABDDEF_@JAAL[JD@Vs@COBMEXQf@KAAHMOX?PTIBEEJGAVKHDG@DKJBA?GCESM?K",
    averageSpeed: 1.388,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11164717138",
    athleteId: "113249417",
    name: "Afternoon Run",
    distance: 5523.9,
    averageHeartRate: 143.8,
    maxHeartRate: 159.0,
    elapsedTime: 2783,
    totalElevationGain: 20.0,
    elevHigh: 390.4,
    elevLow: 371.6,
    type: "null",
    sportType: "Run",
    startDate: "Fri Apr 12 16:48:37 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [49.44311, 11.848175],
    endLatLng: null,
    athleteCount: 0,
    map: "mzwlHabigAMyA?SDi@H_@FwANcBCqAJ{ABmAN}@?}@V{D?c@Da@BoAJ{@HmBVmBDgAFe@FMZQJ?RDXVUSIAY@ULAAHWHy@Aw@F{A?yAAO@QBCT@l@j@j@IROXYPYt@}@\\]~AmBL[Jk@H{AB[FUJUrA{BbAsALa@Bs@BQhA{BAIUUIOQe@U}@M{@EmB?gA@ONo@Jq@?c@Gs@?]Pi@b@yB`@w@Hc@LcAFUj@qALi@N{ANc@NONI`@ATO`@g@TOFKNIPEbAQZBLHr@l@b@LN?l@Qf@_@Xm@V[`@An@DZHVPlAhBh@~@tA|AVPVFp@BRAVIb@[b@m@z@wBh@y@f@c@RMREHKLGVKh@ET@n@APBNHh@f@f@r@AIYSi@k@UOm@Mq@ASBWFeAf@e@Zg@n@[b@]p@Yt@QZSR]Xa@Nm@?QEYKoAiAaAaBY[w@gA_@Si@G]KODWXMXGH{@h@[JUDK?_@Gw@_AYIo@BUFgAr@s@n@]DWRWn@UbB{@dCS`BKX_@j@In@k@~B?ZHv@?NCRKXOr@CTA|@@r@HfARfAZbAb@l@@HAH_@~@c@t@CLIz@Qh@cBzBm@zAIZKn@Cj@In@GPOZy@dA_AfAMTWTm@v@SRSJ[H]K[WOAEF@|AItB@b@@HHDZKYNMICO@VAd@O`@IZSjBCh@M^ANCZ?v@MxAGfAOjBB^OvBEv@@ZEn@BPCdAEXIpBGTOrAEdBKVCV@x@DH?LK^",
    averageSpeed: 1.987,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11158610951",
    athleteId: "113249417",
    name: "Afternoon Run",
    distance: 4008.3,
    averageHeartRate: 139.4,
    maxHeartRate: 151.0,
    elapsedTime: 2116,
    totalElevationGain: 27.0,
    elevHigh: 390.6,
    elevLow: 371.0,
    type: "null",
    sportType: "Run",
    startDate: "Thu Apr 11 18:29:51 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [49.44303, 11.848305],
    endLatLng: null,
    athleteCount: 0,
    map: "}ywlH{bigAEE[LFUGaAFgAAi@B]TgBF}AJoADkALiAD_CLmB?c@NeDLgADsAPoAFoAD_@JWXI@CCwADyA?yCLGL@PJJLTFTAVI^UNWZc@TOFMRQRYZWd@s@TUFKNo@Ba@BcABQNi@LWVc@LYPUXi@l@q@HMTs@Dy@fA_C?OQSWa@GQ_@kBGo@@m@I{@?k@`@qB?[G{@Ba@d@gBTgAXc@P{@Ho@p@mB\\{BNc@ZUPGLAJEx@}@VOnA[\\APB`Ax@NDZBP?PEbAu@RGg@f@k@VUFY@KA]Mc@i@OKME]Ae@FWFYN_@Zg@h@KDS?KBWPILMd@Gj@UlAs@pBI~@Id@c@|@w@~CATJrAIZO^Or@DrBAf@Bh@b@rBPb@`@h@?N_@~@e@x@EVEv@ITQ\\kAzA}@`BOh@IlAYjAKZILi@t@o@p@[d@[X_@j@e@h@]H]@WMMQOEE?CDAH@p@AzAEbBBHDDHANIUNEFELATUp@Kv@Cn@WhAGl@AdAIl@KvBEREv@Ep@@r@MbD?RCl@Kx@AnAGj@GpAQdBAj@KZAT@l@",
    averageSpeed: 1.904,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11107416945",
    athleteId: "113249417",
    name: "Night Football (Soccer)",
    distance: 4627.3,
    averageHeartRate: 136.5,
    maxHeartRate: 180.0,
    elapsedTime: 3981,
    totalElevationGain: 0.0,
    elevHigh: 332.0,
    elevLow: 329.7,
    type: "null",
    sportType: "Soccer",
    startDate: "Thu Apr 04 21:00:27 EEST 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.770096, 23.634766],
    endLatLng: null,
    athleteCount: 0,
    map: "axm|GgdgoCIJ@DE@FAKYB@@QDd@A@MKU@LGHLAKHFDHOG@IFLAIM@FEFDCCEL?EJABJ@SEDFDM@Kt@Jq@AHAYIA?D`@KBNDCG@@BAEGNE@BOB@E?D?EBBBHYARIA?KCFHYF?ON?FSPCJDDHWGSAL^MG?AQGB@ICJPE?`@E[DJBICGa@\\AJIGCFP[KZAOb@SD@GFB??RLNJAU?EEFG?GOOFAKD?DVCMDAGDVIPHEC?DEAE[O?FLFTMIPAML?DKEBCIIJA\\Fc@ALEBDFMSF?@DIHEGDKB@E?D?AKMVCPF\\AUTa@K@HFDSMBBVCCAFD?@OHFEBCWAFBGL?IDCN[DGOVACDDLf@]@MAJFTQEKH?KAJBAE@AKF@CLK@@PLAIK?GEBDNCCI@?GAFJB@IEGCPD@IEPMEM[FXI@HQA@XLYGRE@FDBKF?E?@KA@@HFJM?B@@IECELF@LMOBRKE@@BDICCRSODQERMOLLPGGMDXO\\ROCKLD?Bc@K@OXGIC??FJCBRAFACHCIM@JCIBDE?BFCFC?@YEIMFALTBHH?WK?LA?IKCHCRLAJIC?I@FUNELLOGF?XHUIF?KSCPEFSGBBHDDES[@DECHB?CGAHHBLEAILCLUHFGDFBBNa@SIv@CGBFICJFCFAWDKFECJNEBKGYG@Ej@P@DC@MSJ?Eb@SLHODGWEH?GBPEFOKKPLJDGa@DJe@FAO`@TY?JXO?FGEFUSf@JIBBEJ@?TQ]@]PBBLK@R?GPQFc@?_@Bh@SXAA@LKIBDE@?PACBI`@MBHW?EPFOIS@DFOCCHE@MOd@UKHA?PFHEBR_@YVJMIVF?JSOPHIe@D`@QEl@R[RMAGOXOFIE@CACCF?GECB?CDBCGBNAGAB@EFXGEEI\\CG@UFII@CRDXJi@@RKFAHLOCAZQHUEA]l@MDKSDJNC@GELD?CUDBQ`@NOE@RIM[HDTGGN?LBAAGDA[FDICVKH@IF@LO?QIBATDBFKA[HU?NKJCPG??KI?XNSL?FG@?KFC?PURDKCKFGEEBDADHYCBOA?FDB?]LKFBRSAQCf@QHLGJDKIEBB?BWGPBMEBDGC?NABSMb@?EKHCLE?X[FZB?S@IN[L@FCCHFHKNCGKADHBPMc@LBEGRj@k@IGCHCEBCDASPEJDB^OCA?JCEWXEYOHh@MECJo@G\\B@KR_@RPAf@UQCDAECB@MBASC?P@BIAJKL@D@K?FCCJSCCHADC",
    averageSpeed: 1.175,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11057905401",
    athleteId: "113249417",
    name: "Night Football (Soccer)",
    distance: 5539.4,
    averageHeartRate: 152.6,
    maxHeartRate: 190.0,
    elapsedTime: 4058,
    totalElevationGain: 0.0,
    elevHigh: 221.9,
    elevLow: 220.8,
    type: "null",
    sportType: "Soccer",
    startDate: "Thu Mar 28 22:04:08 EET 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.077297, 23.579594],
    endLatLng: null,
    athleteCount: 0,
    map: "anfxGmk|nCQ?EUKR@GHH@IGKBNE@@]J@V[CBJFOCJIEp@QTQKJQCEEJH?GJJI?ULBBUW|@BSMVCIHH?[CVFC@QDGOd@EKNYF@G?AOATDWAJ_@XFMZE?IAZFBGSLWGZOFZa@[NOVRKGCJI?MJEE^Jo@IBBTMRI@G^DOXFDKCSM?CEAFFHFg@JAFLGJOLDGC@DCEMEXG?NBSHAKTFQI?GPa@PMAPUHF?DPWNEFFFEB@JG@NKVg@F?Pm@AZa@n@I@AQG?LSIF@FHg@VQ@d@B?[LXa@AZUPCIALEWPE@K[L?O?DHEHQJBSd@@YVIOVW|@Ec@G@h@k@@TKBATPa@AQFBI\\E?IKAFGIJLId@?KBDFa@MACZIENe@PGJDEJEKCBK^@SI??KN?UVAV?WJAJWCADAYTREMd@CWPAD[LACFFFEBBIGAEXCOIHX@?k@EF@NKFKh@Za@COOL?RE@LIBYWZ@ILAJQEAM^SBNOJB@OQd@KQHKTBFSSVGKBGCNJHBGEM\\c@q@dAI`@?YL_@FAKPBACLBRL]COJBC?FCE@BOUDADHNU`@Le@DBJOBPGGHMAFSGKb@PaA@JRAQB@LAMGCDAJPYf@PBFWEc@DLOr@BADOCGHWENFDg@NDLEJJa@CBHIOH@HQIV@G?CLLQMHJB?OGPGBHARQBUC?F@ETPq@XGELIMUj@ESEAERD[PULKDLBGe@z@DWLYEURBIn@BBAH[?PE@I?JHEEIAH?STEAFMXG?HeAA`@]p@@VBOIIBOSZPS?MHDAW^o@MHHDEr@Q@DO?XDDYROKd@i@Or@DA@e@N@MOFPETDFHe@NGDUQBCLOCCN?MI?FCCZSNFHEOJ_@DXUh@L_@AXEC@GQNF@@KBDEEF@?GMBLCEHGCJKGFD?GFBDNGIKEBDDGBDKRAOX@HL]AE?FT]CDRo@?NBBUg@@v@M\\Vo@GPUAPBR[a@NED@TKACJLEJU@s@ZJU|@ICFOI?EXNM?U?NKNAOUHd@UNWAOSLIb@]BLQBf@EMVi@E?NTRMCVCKFOG\\GDIO@IKEFSPGKACJDI@HSjA?a@CNIBDSPWNw@FXEBEKD@Ej@EI?b@IDKMDAAJDOBD@QETCQIl@CGj@aAYf@TAIGBi@J@EN]J@TI@IVHIBYARBBD@DGCURFG@Na@UDAp@H_@C_@HKIRDKLAS\\K@BMNA?NOx@ULJHCFG?HCGAD?O][MVg@",
    averageSpeed: 1.385,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "11046514287",
    athleteId: "113249417",
    name: "Evening Football (Soccer)",
    distance: 4737.6,
    averageHeartRate: 124.4,
    maxHeartRate: 166.0,
    elapsedTime: 3662,
    totalElevationGain: 0.0,
    elevHigh: 401.0,
    elevLow: 397.6,
    type: "null",
    sportType: "Soccer",
    startDate: "Tue Mar 26 20:01:51 EET 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.775787, 23.576834],
    endLatLng: null,
    athleteCount: 0,
    map: "s{n|Gez{nCLDEA@K?NEMZj@ICBCE@BHM[CG@IBF@IEOHBBJ?EGAEf@D@FCDIMYAJ@EJ@I?FAA^B?CUB@?FII?GBDI?CJLAI?LYKBIPTLI]ANBD?KF?CBEEC_@HAI?Dh@GXNa@CCIZBUKUEi@BRC?FL@HBGGEL@@VBCE_@?HG@JKAMAZSj@CSHSNGADOOJEBOBFCLAOCFFHKQBHFQPCMBDXGWCBFDCL@C@OMV@FHADXA@AEI\\S_@LE?YAHFCC^IUAa@FKDLGZFOKP@FBECa@BAD\\CFCECz@@i@HB@HB_@JUED@FC?AGFZEm@FEEPI?H\\CH@@CAEWFXU_AF@@LGRDf@CNCgBDHDz@AC?JEU?JFADj@GAAL?GGCJ??WCNC?DAAGDR@GEYDi@E?CJF@@j@D?E@Ga@J@EDLo@@TIXCCFEIL?IDb@@IAR?GCDCYJJ@QG@GZDMCg@IZ@b@N@L]EHSCLQAPCSCDKKCMHI@F@Q@VCNB??JKBEKB@BYN|@D@AIGJIC@e@HICAIFHBK\\Da@BCGb@GFDEHFGGBCIQF{@RGGh@Bb@Fg@@FINDUGHMDHZCaA@JD?OE?TLR@XIAEQAFBOFAC??EBEB@EKFLJQBDII@QMnAEDRqAAC@LI^Dq@Gr@BTGJ@JK@BYD@ADBCKBDLCCJAGM@BGD@DG?FC@S?LJHKDB]FCHMCAFNEE@UAEEDGf@LBD[AEOV?PL?AGEIADDOEUDLGLB?ABBSCQDe@E@C^A]@EAd@ELLDIAAGB\\EGBSICH?CICHLz@Iu@DL@EKLFQ@IGKDg@CPHPMB@D?KBBDj@AXSKNe@BFOXFY@JMVLGLFBOIEAUEHJVOLEO?MLYC?DDEIDMDAEZ?^L?@_AEMDLCv@IAAJDBBC@KGFLKCAIw@MSL^AH?UFLCf@IAD?Va@CDBNSUBHBCINBHBMMXJC?EE@FPKHCUJ_@MRJ`@BKK_ADUClBCQ?OB@AC@L?HCABOAPE@DKA[\\}@MDFRKn@Ow@FPEXHD@VFEWIA]L[?p@KPN_@FDD\\K@S]LGBi@CH?VFVD@MJBJHIMo@GC?bAD?CFDGC[DHBJQ@HM?uABj@Ir@Pq@EEHNMn@@w@DMEN?JJy@EHEA?JEKD?FRCABCCY?VIPCGCPB??FDEMLFI@m@EBDMGFFF?HLIEICZBD?e@CJHZWVDNPNF??MAFAE@C?V",
    averageSpeed: 1.36,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "10714130674",
    athleteId: "113249417",
    name: "Evening Football (Soccer)",
    distance: 5167.8,
    averageHeartRate: 118.3,
    maxHeartRate: 160.0,
    elapsedTime: 4052,
    totalElevationGain: 0.0,
    elevHigh: 332.6,
    elevLow: 330.4,
    type: "null",
    sportType: "Soccer",
    startDate: "Tue Feb 06 19:01:51 EET 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.76986, 23.634167],
    endLatLng: null,
    athleteCount: 0,
    map: "qvm|Go`goC@D?CEADB@IFDOVEOD@AGJA?NEBASDJCHBIIC@EBFFO?IGh@MPISUP@DPc@RHMLBKPCBMBJMIHGEA@BINMHHOD?AH?GRFS?GJRYGNG@CPd@g@MA?JKFGEIKXSF@Mb@U\\HUHCAJD[EDB?DFCMDRITCMHc@TBCHU@BSJVOGF@DGAQWj@BIHLBUEORFo@X\\BTe@ADFJOCOFWKPFPMAFLBW@W^p@w@E?ALJHGBIADKJEKRQ?Hu@DL]VCTIWl@R?GAFGI?WBBENBFEBCQHHANMNDQKIOBELJCNWPRTABIOBIJ@WDLe@j@G?h@q@@QGIHOI?Id@IAMPBMC@FEDJH?HUBFFMANEB[RMAHDRQ?P@GBBKLCIHGB@@JUBKJb@k@Gf@@EWDEE\\gAB?ADDBBCe@b@SGFAVNEQIFPGBF@EEIKHLG?PIL@IJ@E@@SNBDHBWGLD@BA?EGDCLBIEKO?KJITAUJE?JL@Xa@BLJBEDAEAHDHBGQ@QPEOFDg@APX@PEG?UCAFTLa@CLBDFGURG@BKPUFC?DHIa@RSIVQZC@DNMY`@I?ATDg@INh@[DL_@Ic@\\HSODBHEOHE@NLQ`@GMBAJBCC@?JFEAEAFDLA_@KUOJDPC?ZLBJUDAQL?AJKFDe@LCGACLHAGVEIHDRWOWEH@t@E[BCg@R@I`@[I@?MNGCb@M\\FQBLF@EFEE?OF]Il@CC@MMF?HNKDBIAJa@R@DSIICNDFOERRIADAEE]TDJS@T_@LF@QDGCJ@BCIRR[^CGPg@EBAGIVAGHECRAIBS?DSD?FJOK@^GICGX@YHIP\\GD?GH@EFCEAQQFIEDGGBHD@I@P[AJEFJ@ACI\\DBP?SCGOBAJIIRH?PLUELKA?HIG]FVSLYD@BSEXHNU@HADMD@i@l@VWDFPAMNEYIVFYHJMNCC@UFMFEAj@CDBCDg@?LGFG@_@R@D^YIDFMJF@GWK@GD@@PP]ENNHUHIe@RR@EAGKAFGGH?J_@FLID@HPCRB@BI?L@EGMHIBBQFFMF?AZUPOEFOh@Y?RWRLu@GBFDCIBZCPCCSDBIFDJ_@FE[d@JKBJJ[AEI@@HNEa@PFE?NHW?_@B@CADQ?VG@?JKCPIIAWT[HVGDTM@NELSGAB@AWJDCLDMFHKF?SC?HPWDGNRW@UERL?NSCGGPAKQJBF@ENHE@J@EAGNCAD_@C??J]b@\\i@b@AOE?FB]?MKOF@iAsD",
    averageSpeed: 1.304,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "10663045507",
    athleteId: "113249417",
    name: "Evening Football (Soccer)",
    distance: 5570.3,
    averageHeartRate: 115.6,
    maxHeartRate: 176.0,
    elapsedTime: 4335,
    totalElevationGain: 0.0,
    elevHigh: 333.2,
    elevLow: 330.7,
    type: "null",
    sportType: "Soccer",
    startDate: "Tue Jan 30 18:59:33 EET 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.77006, 23.634893],
    endLatLng: null,
    athleteCount: 0,
    map: "{wm|GaegoCVGa@d@TKAKGVDFK?@CCGi@NAFREJYL@CBFUGHLDF[F`@JXCI?L@ECEG@AFHUQJKAF@K@DLBKDBCJ?EB?WHHi@SPDGCPf@W?IIRDDGGBDQJBRGCJOGKDBTOMOMDDFNSEB@GE?CHHHOELTIMFDQ^ICNMHUa@l@HIWKd@I?MFDIKWXNCAKDCXFOEGFLSI?ATHEE?J@@HQMYf@BFJq@HIHLFAUEJAAL@WW`@N_@QVIEFX^?JOIEAUG`@BCIBERD?GEANDUE?@FDM?JAGHODABNGGBPGLIHDYBJH@W?AHMD?N`@w@XUICDABB[\\HKIEHHI@BOGI?ZRFMJ@WCBDHK@L?CILa@DHK@FIFRIAMBAHAGJILJ?HUN@DCI_@T?H?OTUM@HE@QEKIVDQDA@HEP\\]K?INETPQC?DBIP?SNSI@HFBMETOPIECLNUTK?FKDBDIMAFHOIZCIDA@YEF@LAERa@GBFMKPFJMIBHBCILBO@NKHB_@PCI`@RYUABSEJZRMEFBKVCAJi@OZDJBI[VFEPc@a@FR??I_@Vj@MLk@i@l@\\Bc@f@\\g@DLALUBZURC]BIJBIFFEC?LHUEJEKUXGAFGVFECFQRQWh@WFAB\\c@DDCGDDEEAMFGBPHIK?@LCNDAMBCNHKAUHI?OIOG^@FGE@KL?GXFPHCGKIDBJEFG@JKJ]Q?X_@B@O`@GAAHWFJc@AHAGUNR]MVEAFBD?QDAKAH\\GSEDDANCADDVOJWBFOAFLDCADLMHXOBDSKX@LWFXa@GYBAMJEJLANWOVCEDOZJGJCM?XAEGPQH@FUQFKVFJQJECHDCOLIWII@FHCENDHWNEOGFVG@DQLFUTD?KHc@E?KZCMBJIALOc@\\HF@^GWGCl@FFK_@LFQAHH?@ODDB]@JCGN?MHBFGFAMEAINC`@?IE??NAGD?GGZe@CJLDHCDSEKBHSF?QGJ@LOEVEBF@EEJHPDKKEITTg@G?Cb@QPUKG]PIBT^WF@IDCGGHMITD@IAEEFL]CVSLHNFQURHSHFOEFAAFF_@CKW`@WHLAFVE?XFL[[f@ME^a@KABUE@@FDA]JIE@LL@XMBOCBFFJ?E`@OOPe@D\\L?[PMHA[^MSp@F]EE_@LPCBJN?GWEZ?u@TJII?QOT?RC@PODFYJBUEJPEAMOBELP?EJNUKJUCVEBB?HCe@Sn@@PVg@IJBACITHFGSCDJCARKC@CVKPE?Bc@NYEEa@Z[FHNP?LGJSQG?GF?",
    averageSpeed: 1.317,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "10663044748",
    athleteId: "113249417",
    name: "Afternoon Football (Soccer)",
    distance: 5337.2,
    averageHeartRate: 146.0,
    maxHeartRate: 181.0,
    elapsedTime: 4143,
    totalElevationGain: 0.0,
    elevHigh: 332.4,
    elevLow: 330.4,
    type: "null",
    sportType: "Soccer",
    startDate: "Sun Jan 28 14:58:44 EET 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.76977, 23.634113],
    endLatLng: null,
    athleteCount: 0,
    map: "avm|Ge`goCGDDF?M@JKBREIFBEEEDDAFCIFDCCBAGDCKHs@G^AMILCABCEB?G@F@GCHFJHEBNC@@DE?B?Gg@KCDNIDNBU??JEBBDJKOBAMFXNQENG?BBGPEERK@KOMINBFD@L[NJGHBB?IWTHQEEh@H@UUHDMMPKBDBEFAMFM]DADNDDIC@VQIMC@JNVKMK@Je@d@P?VQCFK@EYJ[JAGXCGCHIOL?EXUDE^JEC]OV?ODJB?BMKDCGNLAMOH@IHRJAYPf@c@AINB@IWTH?IHDAQATUKDGTOIN?GJFHNKNa@WXPREUH@?E?H@]B@I?AS@I@R?WMd@?JDFUIPRKDJQMf@BINIGFAQKIKHHGEIJ@ETHEOPRYG@TOFUG?SV@BAEBJMMANJNESKCE\\^[BICINKe@f@AJEBBS@BCD?QFD@LK?ROF@CHXe@a@RI?DSB?@RD@FOEJBPCDOGOODBCFNM@HGA@JJCGJGQL@EFHOCFSDDZAMD@OKDODHFCN[BHI@T[ENE?@LI@DHAQQ?FNIJFDE@EJBQHEN?@RCOMCBFDOTQCAKHE^a@?VMIEKLBHXQ@DECCRMBNUDBCCEJ@NCGJOIICBAPBQFRCKEHNCRYIQKJ?LMADHP]KXDEPY@OGPFKBD]b@@MCJBAGI@LNW?FDBg@h@R[JCIF[CZ@IQC\\?IHACFAMO@DD@IMETKG\\BU@JPAAQUZDF@WBTCUAFKDF@DINVTWCFKGGXJOSFTMBI?IKKRHDNIO_@b@GUF?@WI`@?QLDKLGKL@GJHCKFBMGMFKL?FFQFVOADKAAKVK?G[r@@LFC?FLKJWKBAIHCDNEBKg@B?CDk@fAH?BJLSBQOPIEFGCMJK?^?MCJOGDAAFBFBGEHp@WCIWNDEAWA\\CAR??OPPF?WAGLTACAIi@CDDF_@RDLWG?HB@LU@@Q?EJJ@r@UMAIPBECECJQBCHj@_@EDBBICIFNK@GIAKZO?HOEDBRO?FFVGUHLO[Fb@MNMECAJIBSA^?LQOLAPJKILUII@BEJJGKC??HGATQMRWEXS?VEFIUH?HNXWL@HDUASNQ@T]PI?_@BLUh@ATYD?M@FPDB_@K@CDDGPH_@LB^PQCKE?HIUDF?EJB@JI@IIANBEIF?OP?DHDBEMBGJPEF[@QMG?VI??FFEADB??IDAE?ENG@XS[TR]LDUDCDGLH@AN?GIGD?ADBGEEJ?BX[Qn@[XUG@H@SOAIHMo@}Bk@{AKU]JG[",
    averageSpeed: 1.32,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "10618798955",
    athleteId: "113249417",
    name: "Evening Football (Soccer)",
    distance: 4656.5,
    averageHeartRate: 110.7,
    maxHeartRate: 162.0,
    elapsedTime: 3854,
    totalElevationGain: 3.1,
    elevHigh: 332.8,
    elevLow: 329.3,
    type: "null",
    sportType: "Soccer",
    startDate: "Tue Jan 23 19:00:57 EET 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.770023, 23.63437],
    endLatLng: null,
    athleteCount: 0,
    map: "swm|GyagoCAVG@CM@LHG?BDO?DBEONJ?DQJAOBFKBBAECHDMDA?DDICNIC@CICUF?LJMHFK]HVEIFQFNONJIHBFJCDE@MWBCFH@SDG@JEEEJMD@DGGLSSRM?D@CHD?`@MNe@CFBAS@FJF??HFC@HSIBRMFA@B@[LF?LKDc@EP@LB@DCJi@FEM^QB@CIGN@FGG?FDEFY@CEAd@BJZ]GIGTPAESLEOH@GICDGXHMJB?MACF@AKE@GL@TQGG?IGBBDABIBFFOCDGBB_@TA\\FUFKGB?DUAd@OIAQXJCATDe@UP@GPKITLQ?GAHFDXBU?FSBDFGFF?II@ULCHHC?IFOE@ADTNDKQPKAAFDJADACKBLIJDCUB@OHQECL@KCAXSDQFRBSOLI?CXn@KB@?BIBe@S?DG?F?DRG?LMLDF_@@HELQD?EFGC?ALDBDQB@EFA]GPE?DEH?HPMOBGD?QBIXDD@SLSFCIFDHDCGGJNQDI^OKTW@DKJHMEIDP?KKIKHB@F@KKJD@G@@I@D?BMJVBGA?LGDFBAUJGCIS?BZDGODRBICEGB@IE@AEDLDGG@GNFDDEEEe@^CJ@MCBLAHI?OVSYRDBDL?HCF?[@HGJTIBMEGUP@ENHBAAMBCDTKPG@LODQNCIAU^EYN@A\\ESF?BMH@c@PELFHJWCDGOM?DGIVK@FL@EREDIC?CIEFJ?TWEAGDIE?HVI@GIIGL]PBD\\UEASd@IMOGR?CNDA@QTHCI@A?NYP@F@CE@^WQCCDDPLSAGDAECBW@RLGBDYLW\\?DDBCPC]BB@e@PQF?ENEO@DJA@JD[D?K?BD@EH?IXPF@FCF?KIAG@?H?MCB@DSSADTN@]H@Wl@H@C?Ls@EK@r@ECFa@AE?XH?_@h@E??Gd@c@CC@MGCDFDMBLD?UNALMAOb@I?BF@MFD?GL]PSJLI@IK@TCNBEKHLi@DCAIJMe@TKRVa@LEQDBPGIAIB?QP@K@JDEFNL?C?]b@DKTU[p@Zc@FOAIBFKNJHGLSFTi@INAT?EYPAEZ[OBTKEK?DBKB@C?KHAIDOBHKBDFHOXMKRMj@K?FKWJr@{@C?ORCFHGEPG?NJ@CQA@KHCAL@GCBJIPFQFGOa@XEIHI@JLC@KK@HGNENBEEDB?E@JE?@Ba@ICOFCNRSNMj@?GBBFWVSBSi@fANh@?IOa@NMDGAGGDBCLCQHECL?AKDCF?La@NBIC",
    averageSpeed: 1.243,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "10570960425",
    athleteId: "113249417",
    name: "Evening Football (Soccer)",
    distance: 4817.8,
    averageHeartRate: 144.8,
    maxHeartRate: 187.0,
    elapsedTime: 3948,
    totalElevationGain: 0.0,
    elevHigh: 332.4,
    elevLow: 330.3,
    type: "null",
    sportType: "Soccer",
    startDate: "Tue Jan 16 19:02:26 EET 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.769783, 23.634102],
    endLatLng: null,
    athleteCount: 0,
    map: "cvm|Gc`goCI@?^ESEA@DMR?M?FE@CIIDNRBKCKBADXGK?GFDGPGGR_@?DGDHU?VIDCABED@ABGGMD@HNRCIBQ@SCCCHFGL[FDBKGJDFAKMFHDBFC_@FB?DMGIJHLBAEDAIDDKOZd@BI?}@Vt@k@j@NBAMDITSIk@KIQf@C?J@DW@DC@O`@JD@ECMEEJQDB?LAFIA?NEA?QDJRCKBCG[RFK@ONBBIHBAH?EGAg@XI?d@YWGMLJJXa@s@V^?DIRDEFBHKFJEGI@HCCH_@DEGC?FLL?FD?CFKQG@@EGDDFOCMT\\UMFCNAEIGTKT@MEQPCOLMNAWPKAALNGLURJFAE??GEAAI@NGA?GALGL?IHA@UDd@M[VROCFJGBB@AW?HHLCBGBIEDKDB@QGPDIAFSPLAAG?F_@FJMLDHIHNKMH]IVSZERIOBVH]JSBB?OJK?IEXIO?FC??M^DOAIRYJBHEEBKVOEB?JMNHQGQMF^CEL@FFO?KAHGFFKCLD?QJFDLOGEDJIGHA@HNg@BFAD?EEAUJCCBD@IJC@IJAMNCCAFFJVB[FXWCFM?GGBRH_@KZIDJIBUKZNMIXEEJHEGETBKCOBOHKDR@KBBALC??YKIHJDAEAGNE?\\He@B@KFLQLNa@GAAFDMD?KPWG?ZJGNUYRDOLE?FEHSPRSHPHY@CEHH@AOHAAT@CIKCQWZ@FZNKCEEDDAEDQAOF?@HQZ?IOQI@CJb@KLICAE?CTQYFNMNBDHM@FAO_@D?DRVDK?WDKD@FKIBSVGAL@JGFO@RH@BQHHAEBCAFMAGHCCNF[TATD@M?FSPBKACOGDRWELJ[BJASBACCONECBJADCAL?OI[PRE@JG^TW?U[^?Gf@a@@HFAFIE@DIIK@I@HK@IVHOT?KC@F?NUJBYBDHOBBEF?VQROCCHD[DEPPJ@?OIP@ECSUI?DJGIHM\\J\\Lo@HE?DEAJDAGDBEMENKBURHWZWCLGMEFUh@D@?NGCBADTGWJNN[AML@CMKVHUCIFD?TOBD?H[GDHEECEJB@HMAd@FC@IEEAFGGTQ?LEABEACMN@GIBHLGUBWC?BLI?BDC@FJHEGY@GK\\LKVFKGWH@Xj@OWBGFOFF_@H@GLBGBFCHC@CA@CCLZi@?JELKBALB@?IQ?Pg@P`@a@JKME?DEAABD\\S?OEBNDQQJACCELMN@EDDa@JJKFDE?FEAEJC@FC@?CADLQN@DJ@EOM@SA@JGCD?EEC?IQy@ECM]Og@?MKU",
    averageSpeed: 1.261,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "10525529149",
    athleteId: "113249417",
    name: "Afternoon Run",
    distance: 2341.8,
    averageHeartRate: 134.9,
    maxHeartRate: 153.0,
    elapsedTime: 1822,
    totalElevationGain: 0.0,
    elevHigh: 0.0,
    elevLow: 0.0,
    type: "null",
    sportType: "Run",
    startDate: "Tue Jan 09 18:52:39 EET 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [],
    endLatLng: null,
    athleteCount: 0,
    map: "",
    averageSpeed: 1.285,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "10519477870",
    athleteId: "113249417",
    name: "Evening Walk",
    distance: 1805.4,
    averageHeartRate: 144.0,
    maxHeartRate: 155.0,
    elapsedTime: 1716,
    totalElevationGain: 0.0,
    elevHigh: 116.4,
    elevLow: 112.6,
    type: "null",
    sportType: "Walk",
    startDate: "Mon Jan 08 20:08:25 EET 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [],
    endLatLng: null,
    athleteCount: 0,
    map: "",
    averageSpeed: 1.052,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "10500493212",
    athleteId: "113249417",
    name: "Evening Football (Soccer)",
    distance: 4747.2,
    averageHeartRate: 129.5,
    maxHeartRate: 170.0,
    elapsedTime: 3716,
    totalElevationGain: 0.0,
    elevHigh: 221.8,
    elevLow: 220.7,
    type: "null",
    sportType: "Soccer",
    startDate: "Fri Jan 05 20:00:47 EET 2024",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.077454, 23.579512],
    endLatLng: null,
    athleteCount: 0,
    map: "aofxG}j|nC@IMXBMHC?LCIJBEOBZBCKSFA?G@VK@SQJIHBKN?D?MBGELCEPMDKCCF@BJCKEHIAEHBMAJL@BG?MCPGCRYOJEP?TIM`@q@MHIn@?[NIF_@IP\\@@DEGFGGCA[UhACOE`@Fo@JCW^K@EVBKE?HA@HNa@I?BMPI@ECHJGJSB@A\\BDBG?JSX?DB@LWg@f@DDCLBIDDMEBACk@QE?GD@l@cAF@?NJVB?SNECHQUj@MDIC?IID?ND@BWFKGEHC?NL[BJLCGNCKGPOCI@HK?NAODG@DEECd@?ML]?HJICZMX?UBEGSFF?DG?EGDLGJBBCSHECCBLEABAFHCj@DKWXDBAIPKCOLo@JSPLMXAKGBBA?JO\\EEBUCS\\OPLMPCI?BKBGh@KFHc@IOJWKt@WF?P?UB@?NECBG?IC?DGH@CD?MEJJEIFDPEJIMLUKDHDCCFE?M?NILD?ADIBHGIAH?E?@EAFLUELGB@D?GBH?I?LGCHBG?EKLKBKFO@DC?IX?LAIC@DBDYCCB_@FADPGN?IPMAIQXEEFIb@KBJWPGXGBBBLg@CQLBCDR]FRWVAGAHG?CHSE@ECZH]@BCE?VFCCIBAE??QGd@KIHGXB?QJWCd@OHEZ@IADOKDDJMGRSE@UZm@LIJLORCA@EQp@K?BKAKGHJWX@DMWH@HBKPKLSF@?NQd@IHAUMAQL?PE@NWCCDHZYQp@AMHIEMEB@KC@BBAPCABD?VBIEEGHCCXEIGJKO?RTC@GETc@BQOVAJHMF?BGYHMTFICACYBKTLZEYb@K?BKDRGHDQEFGK`@m@Mf@@CAGFECGHKCN[h@MGMPCG^aAVQSNNCWv@?DBCCMBE@DCQPIYh@D[FPF@CBMCZQAKQp@@AICCJGABBG@GEAKF?PQFBJa@?HBBHI@Ka@v@BY?NO`@?G@DOJ?KPUQL?JHPAa@E?NIGRM@JA@FCE@I?DDMGDBDADDSE@@CTIUJEPD@CJB_@DBAJAO@ADLQLJi@RURBECa@THCCVKTCIJWGAEPN]C@CLIEDK^SUz@G?JWGQEt@Hq@CJDDOJCCJ?JUGJFI?PIGCNDOTQEMCLE@DBAIGDRd@LYL{@GE?\\Y`@@INKFB@KEKHAFHAHe@j@G\\@OM@RQEKE@JFCELO@JMLICKXVc@CVBGQDh@kAC^S\\BL?MBDENCALc@GEFGMRNVCKDC@a@@FAORFBWSRANMZ_@VEKB??FFD",
    averageSpeed: 1.295,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "10447005673",
    athleteId: "113249417",
    name: "Night Football (Soccer)",
    distance: 4395.4,
    averageHeartRate: 140.4,
    maxHeartRate: 187.0,
    elapsedTime: 3623,
    totalElevationGain: 0.0,
    elevHigh: 221.7,
    elevLow: 220.7,
    type: "null",
    sportType: "Soccer",
    startDate: "Wed Dec 27 21:01:00 EET 2023",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.077118, 23.579628],
    endLatLng: null,
    athleteCount: 0,
    map: "}lfxGsk|nCNU@KCPIPLKQNFPFIDJQDBACOHJGEBHKC@EBHBAG?@UELI@@DPEKKBEFVIDCGBAIFJK?KI@EHTU@MCC?TS`@DQEE^MIBBMER?MH?Gc@CZBB?REDRCAMEHEEONDFDCGAB@AUDDMDGNH\\?e@Xe@AZEBEGPH@CKFQGBNGOBMF@EDBBE?CUHLATDCC@AL@EE@BD@[IA`@KEI@PEAAEZL]INCCCBII@HJIBNAKB?K@FIFNQKCGQFHA^CWLBEFBJDQEHGYF@BTECF?QL@BAQJEC@@DBA@GI@ALHAQREAJSJEGLAKF@GFGAGZBSIOBAUZBJP_@?LH]MZSRHKFSRIBBYz@IDKGDAAIV[DICAAf@KTHAOC?WHIGK?LH[G^DCG@ATHUBD?MCCX?Bc@CD@TQXGGBJICUFD?ZWQPAH@UD@BIBDEVDa@T[FBMb@OLIEJ?GQR_@LDCLECDFKLJJ?MIFASJSDHKH@LEY?\\GE?EJ@FHCa@HFM`@BDEE@EECN_@G@EZG??EJACMD?O`@C?R?Bc@K?P?AGE?@RH@KDJ@EIIFCAHEDHAOEH@GC\\DY@DEODEKBNBCHDLKIDC?QELDELFIIBDG@@IDDI?BHAMF?ID@HFKISCPHDCDD@BGIKB?ACIL?DFGBJ?ODDMDDSBFGPO?JKFHKX?IJKBWDFI@K^GDYIHGHQGBI\\DXEMB[N?FG?GCBBGF?AHFEEPKBD??JSCLPAMHa@CTGAHF?UCLFBEYCTLS?ID@EGKVF?NQOJA^Kc@BGSb@@FKHPWBHFGBUO@CE@PELAETK@OL?ELQXKH?DCABWJQFB?FHWC]?XKZDEWTCJLLAHI?B_@FMCAH?IIBHARCMZCKEFKNK_@XMXBDD@MMPY?UDIEt@No@HADFO?DNTIm@h@DDGABQ@\\Pu@AXBEMWBJE?JBEENa@G\\GOBNKL?OBAAFAIBDIp@C?B_@L]NEDDM\\IDCUN@IIATGHAIGD?FLI?OVSG?DHSF@MB@CF]f@\\g@B@CJEAAJPBDG@IQAGHALBAATIIH?BI?FN?@e@EPSF`@k@I?CNHROJAWEHFCO\\?QNWKf@DITGg@f@Xm@LG?NEKL@QBII?QHJA\\Y`@GUE@LC@NB?G@?]DACGMJFWHZHEQDBJBCAIED@R@SLg@TW?RUh@E@DFQCP_@LBKREEP[?OGBBFIVEAZIKM?SDFCFBHF@AWGFECALDEGFBKJPC]CVKPGEKPDO",
    averageSpeed: 1.266,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "10332898380",
    athleteId: "113249417",
    name: "Afternoon Run",
    distance: 2500.0,
    averageHeartRate: 135.1,
    maxHeartRate: 168.0,
    elapsedTime: 1097,
    totalElevationGain: 0.0,
    elevHigh: 0.0,
    elevLow: 0.0,
    type: "null",
    sportType: "Run",
    startDate: "Tue Dec 05 18:15:25 EET 2023",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [],
    endLatLng: null,
    athleteCount: 0,
    map: "",
    averageSpeed: 2.279,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "10328451583",
    athleteId: "113249417",
    name: "Evening Run",
    distance: 4092.8,
    averageHeartRate: 144.0,
    maxHeartRate: 157.0,
    elapsedTime: 1805,
    totalElevationGain: 11.0,
    elevHigh: 115.4,
    elevLow: 107.4,
    type: "null",
    sportType: "Run",
    startDate: "Mon Dec 04 21:06:22 EET 2023",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [47.20444, 19.736813],
    endLatLng: null,
    athleteCount: 0,
    map: "wrb_HazmwBMIGMW[g@aA{@mASg@@M\\_@H[^{@jAsBY`@]l@g@hAg@|@GR?J@HHDDNd@n@nCjD~CzBFBhAFx@LR?\\Fr@DZHl@FNDF?JMLKRARHPNt@VXNpAb@`AVPJp@TdAPj@b@Bb@?d@AJMVQV[XQ\\ITQdA@ZFh@b@jA@VCd@KX[ZQJc@DODOJKRIZ@XDXb@dBJZHLNJR@JANO`@uAPa@`@q@RS^i@LMPET@r@^NBPCFMDY?UEYO[QWMY_@oAg@{BOc@a@u@SIW?GCES?SDIRQRKF?^Vj@p@ZXn@pAlAlCLn@?v@Au@G[KGIIOa@q@uASi@Yi@Sk@OQYUa@c@WEIGGSKO_@Sq@O}By@{Ac@_BYe@WGAUF[?wC[kBK_ASu@a@aCcBy@aAeA{A]m@Os@EIAAA@?HZr@|@fA`@r@b@j@p@p@\\Vf@ZpA|@n@JnCR~@NxALFAV[P_A",
    averageSpeed: 2.269,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "10278372633",
    athleteId: "113249417",
    name: "Lunch Run",
    distance: 18494.6,
    averageHeartRate: 151.0,
    maxHeartRate: 168.0,
    elapsedTime: 7859,
    totalElevationGain: 247.0,
    elevHigh: 437.6,
    elevLow: 225.6,
    type: "null",
    sportType: "Run",
    startDate: "Sat Nov 25 11:47:10 EET 2023",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.077778, 23.563904],
    endLatLng: null,
    athleteCount: 0,
    map: "aqfxGkiynCQQ?NKZMH_As@}@XiBUCHDDBGY^uA|@MVm@^gCzBYDg@\\_Az@i@\\uAtA}BbBuAfAwG|FoGxEmN|FuEtB}MpHwCpB{CrAmCdAyGpBeHlCiAh@_ItEuBbA_ExBiPfJkCpBkBjA_Ax@mBbEkBpEwBxF}@rB`I_SdAyB`@g@vCkB~BiBjEiCxBeAnBmAlXkOnMoEpDeAbBu@|C{A~CqB~MqHvGyC|GwC`Bk@vByABFTrBNp@JlAr@|Ev@jGjA~FfA|DEhAQt@s@nAw@vBiAvBc@nAE\\xBzT\\nB`CjHh@xBN|Bh@zExAbHl@hIBHVCp@s@NWJsBIuDHYF@Z`AlAnGlAjFj@vDj@|Ed@pAdAvBUt@E\\HfAXvAV`@fAb@hBD~@GvCq@r@o@|@yAJKNAJNB`@?fCEl@Hf@R`@RTl@Xn@T\\l@r@jBdBxAXz@?lBJpAJh@h@x@tAx@n@n@P?`@i@xBeAvCaAlDUfBWj@PRb@|@|BRhA?h@[|AUl@MNiAb@a@VKVSjBKVi@n@{AbAOZCXDRLNtC~@nD\\PPVd@DZCf@Ub@g@Vm@`Ao@r@eBh@aBr@u@@WF]Ty@jAy@d@O`@EdAJzA\\j@\\LdB@zA\\fBT~Af@t@H|AI|CXjAOvAmA|Ae@vEmBRUhAoBjDwDtAqBF_@GGUNsChCwCfB[Fm@CS]D]lAsAfG}Fv@_BxAuCX_@z@o@`BwBn@yAj@eCt@cE`@kAbAaAn@c@v@YjAQ\\S@HLWv@S|AmAdAiBz@gA`@yABQGKu@Gd@ARSZINQDSIy@Ok@m@s@c@eAuA]YQEY\\oCn@iEr@aCzAaD`CoD~AqCf@gAh@qBV}B?kDOsEG_ACGGk@A}DDuAAII@NmAPq@vBgE^sABg@O{FIiAsBqHUkAOgDu@kJsAaKEcBFcHCuAI}@q@mCy@{B{@{@cAo@kEqBc@c@a@g@w@aBg@u@g@aAoB{CSw@c@a@u@iAcAmAyBwBe@Y}D`@aLt@c@OwCDw@I]@GGW@e@Oo@w@y@KsAs@OASUSGe@x@c@xAeAdC[z@O|@e@`AK`@_@n@WD[l@e@rAQJ{@G_Bm@g@OsAEm@k@gAKy@WQWYM[o@e@c@k@u@K[_@Wy@eCs@cA_AmBM@i@v@WR",
    averageSpeed: 2.36,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "10264766112",
    athleteId: "113249417",
    name: "Night Football (Soccer)",
    distance: 4796.2,
    averageHeartRate: 106.5,
    maxHeartRate: 150.0,
    elapsedTime: 3679,
    totalElevationGain: 0.0,
    elevHigh: 332.1,
    elevLow: 329.7,
    type: "null",
    sportType: "Soccer",
    startDate: "Wed Nov 22 21:04:21 EET 2023",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.770226, 23.634563],
    endLatLng: null,
    athleteCount: 0,
    map: "{xm|G_cgoCPEBEAEDC?DOHBCKMHFOJEGBGFH@O^O]\\B?DQM@AHECD?GHCGl@[DMCCY|@DAGENVDa@NSBNSBQZFIDWKYZBAYHPCVAGU^?GE?HNBGN?BI?HOAAGOP?ZGa@@_@ZF@F[BFGGPCOZYSl@MHFQHJCDK?JMNHAFV_@WREC@ND?EQGCMNARPMEQGCGRBLNSDBZYA@DNEGELIKI@AH?I@FJ@PIDOGA[TJEGEFGGFBDQXYUDDCJ@K@FF?AIG?BJFCIAJIIJ@BE?AMJACD?DACBEAGDFKFB@CG@CLJAOIZAIDKIBDCCC?NF@EEBKC@DFK?BCAFB@EADKE?PB^KAa@M\\g@Gh@MBJG@@DDFKUGn@F@AEXQANESQLBAAKFCG?EKNHBOQLDZLKGYECRBIDEP?GG?M?IHXSOAH@@CCAAHBHCJEEH@Ka@Ab@B@TJLQQ@AKH?DHJDE@DYIHDBEP@MM@?DHK]EADHDCHFGHHC?PGCABGGSGAIPH?AEGBDFDECC?HBF?S@JJBODGKBFD@@_@?^DDLG?CI@@CCOKCSJDFb@[BIKHMEBNIJO@EILAGPN_@?XKEXWGBMf@CEDS@PIQAKRKDKAEEPID@NJAHKXJKHGQ@LB?GGCPG?MVEG?GFREFAGDKLDDGII?FBYSRHNL{@RNBHOA@DLc@OZFCEAAIK^LGSVEBAEAFBc@EAFU`@?AGECFDCUAVACB?@PERE@ASQA@FZ@BFBGEJWN@M@FH@IG@IE@?G?^J]Da@@XFTWAUH?ILMGJDGPBDSBA@FOIGHCVBYKACHDJT@BWCEDAMVDIFJBEI@DRAOFQ@FIJ?EKGPBK@YR?PEMBHBMHABFTWCA?KHSAFCAOZM@Z?JMGTGIBLGHF??KMMHITFBFSB?GCHCMFIE]CLHPEJKBJQHHGOGF?IOf@EAAKLQMEPALPHABIEEKHEE@BJG@PK@R?MAFFFGAEE?KTQJ@A?HLENUELQSBO@L@KLCADIIAHCEFFBMUTEGHGBBCRBBP[[L?HD?CGWDNOJ?HJHGU\\GOOITCQJD?AIFPABIOLIWH?HHD@FDK@Df@UCJ@?BCYFBBAEKNZQBKI@CZCE?KNUEI@F?MDFED?EGAJIE^M?HABL@EEA?H@IBHSDJGDQES@IIf@E?BBJOJAIPa@VGGRIACJ??FDC[ASN?FDC?MBF?LFIf@KA[EAKP[OJG`@DHE@FIDKVKDCAFIYDGKFLD?CSPQX\\FS]VDQCDBLJOMCJFHMRNKEFCEBAODH",
    averageSpeed: 1.331,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
  {
    id: "10264765677",
    athleteId: "113249417",
    name: "Evening Workout",
    distance: 5287.5,
    averageHeartRate: 145.6,
    maxHeartRate: 182.0,
    elapsedTime: 2042,
    totalElevationGain: 17.0,
    elevHigh: 462.0,
    elevLow: 333.8,
    type: "null",
    sportType: "Workout",
    startDate: "Wed Nov 22 20:20:48 EET 2023",
    startDateLocal: "null",
    timezone: "null",
    startLatLng: [46.754513, 23.578726],
    endLatLng: null,
    athleteCount: 0,
    map: "uvj|G_f|nCFCDDF]JKB?b@Qf@ENIF@^WZETKPAJQIgAWwAKSGs@Oe@Oy@MYE[IG@i@I[OkAi@sC_@qAUkAKUUQGSKOAI?GDKNIb@s@@]AaAa@eCQyBUmAASG]@KIi@Ay@ISK_AUaCEeAOuAEmAG]IiBGWBy@CKCwAGy@?[Ii@KaDCaAK{@IwB?o@EcAE]?[Do@GyAB{@DMh@QFQCa@@]Ka@GEQGGGWMc@c@m@gAK[Os@GGI[IOa@]c@I[@OFO?]Nc@HWLg@Lo@SOWa@cAUWYWSKQGOAUMI@SQKWIGIMGYc@YOUI[UUEOYU?GQYSSKGGOSYYYMI]o@YSM[Me@QWMI[e@SSK]AKG]P]Pk@f@{@?GDg@La@AGWg@Qy@O[I[Mq@EIEa@EEGi@GSMgAGU?I]mAc@WOUGE]AUKUAk@Uy@KOGI?q@KMC?CSAMII?KEMi@a@E]KUCYIEG@]EEOCG@GACGMq@u@kCM{@IWCQEQIIKgAYsAEu@Mi@M]AUMy@[iBYYG_@IwA_@iD@KGm@Ms@Go@S@CKDSLK?K]iDKi@GqAASEGAe@Mo@IqACCAq@Gg@ScAI}AKQCa@BS?[Oe@GaAIY@u@Ms@C[EI[LKIMc@?OMs@A[Oi@AY@_@GmA@a@Cc@@i@BEEo@?e@DeACgACY@gAG}@?[BQCiA@]GsADm@E]B_@@}@CiB@]Ag@CIAsBEc@HuBGm@?SAM?{BCS@u@Bq@Eq@BMJUBA@@ACADS?UAQFCCGo@?WBOGWOWi@OISWaBGMSMOQq@kAECOYAi@OWGSOQ",
    averageSpeed: 2.589,
    maxSpeed: 0.0,
    kilojoules: 0.0,
    averageWatts: 0.0,
    deviceWatts: false,
    maxWatts: 0,
  },
];
