export const mockActivities: any = [
  {
    resource_state: 2,
    athlete: {
      id: 113249417,
      resource_state: 1,
    },
    name: "Evening Football (Soccer)",
    distance: 4454.8,
    moving_time: 3445,
    elapsed_time: 3663,
    total_elevation_gain: 0,
    type: "Soccer",
    sport_type: "Soccer",
    id: 11652391604,
    start_date: "2024-06-14T17:02:16Z",
    start_date_local: "2024-06-14T20:02:16Z",
    timezone: "(GMT+02:00) Europe/Bucharest",
    utc_offset: 10800,
    location_city: null,
    location_state: null,
    location_country: "Romania",
    achievement_count: 0,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a11652391604",
      summary_polyline:
        "onfxGwl|nCTAKHFe@CJBJGALODBCRBAEHCA@ECBBME@DPKBH@IJDEE?BDCLYHJGFWBJ?KAPBBG@DIAGEDBHCOVCLQWX?FGE@U@BLI@JWNEOBEJOJ[BABLGLFECR@ECU?LIZEELEOc@BFKNF?HQBDUHB@@EGGDFGHNCINFDCDCSDM?LKAHE@W?ZKJJQGJF@DUB?AOB?CCKXOJIX@CCGLEPWCGJSD@BHC`@IBT?SPES@KD@CDJJI@?EDHG?]XB?GLTm@HCIT@DB]AVBAY`@AUPHHg@GACHAGBAGZBGCWJBIFGGHGBJJSLJa@v@_@UJKPB@M?JIGGHLOE??ELKHJAT@[MP?MDFALCGHEIRHc@PY?KDEBDAJGP@FEVAGDKAFI?MVB?KKHIE?JYCGALFN?NUVGALO@^OGCKBM?NCDP[JK@KCFCADA@KFCJW?I@FG?AJEADB?\\IGSTB?DVELFACEQ@FML?EKV_@Id@KB@EL@?[?DLB]\\N[DUQBBUDABHUJHr@@_@FG?LQh@BAGBL_@AQBSVGGJGRB?CABECXKJMERe@J?GC@VI^D@GI@W\\y@Dd@G]DAQ^GA?E_@JLAJc@AFA@?EBLGLBF?JAKHBX[KP[JLKRCBQAQCAINHMD?CE@F?GQD@VDWMCF?AJRFW\\ANUp@AQRa@HEGJECCOJ?KTWANWDWBCCRBKDRC?HFRUB@NOWj@UJFGENAIFBCODKK?MM?CGh@SF@EH@HGCGJ]T?HQN\\G[BCB\\GMDEEIC@L?CH@DAODDMIBCC??JFLDMCDAKBTCEHKAFIC?BC@@SBJCDAABFCID??DCCAM@NDEE?IQKTDFALE?RYBHC\\OLKEH?CQAJXIETWA?KF?E?ALNAELDWB?W`@?II@HITs@POOCMh@DDBLQ^AKRi@BPKXE@?GICJ?HMCQGFIABIFEBBGD?TE_@Sz@D]T[BD@GD?APG?F@?PBCCADBIi@DCL[@\\IVLF?IBAMUJAGXWd@GHCAHm@Ra@FD?HGL@NQ`@Bc@ALGBIK?KTWXCC\\ULBAEG@e@FBIVWX@TDAFc@Cg@HANPL??FO?Ud@?QHWDADVCHCA?MBKEFNNIPB?CSSf@IDCWEHFACQ@ZC?BBCB@KFJDEGJGSBHFDHQEJ@WLEANMMIFAJ@MC@D`@B?EFIKDBCBHBE?AD[q@J]Zi@NKHQXS}@bA]n@\\n@[k@La@\\m@",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [46.07736, 23.579804],
    end_latlng: [46.077405, 23.579968],
    average_speed: 1.293,
    max_speed: 5.24,
    average_cadence: 64.7,
    has_heartrate: true,
    average_heartrate: 139.6,
    max_heartrate: 180,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 222.1,
    elev_low: 220.8,
    upload_id: 12433749355,
    upload_id_str: "12433749355",
    external_id: "garmin_ping_347802536896",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 113249417,
      resource_state: 1,
    },
    name: "Evening Run",
    distance: 5438.8,
    moving_time: 2647,
    elapsed_time: 2690,
    total_elevation_gain: 265,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 11628851514,
    start_date: "2024-06-11T17:08:04Z",
    start_date_local: "2024-06-11T20:08:04Z",
    timezone: "(GMT+02:00) Europe/Bucharest",
    utc_offset: 10800,
    location_city: null,
    location_state: null,
    location_country: "Romania",
    achievement_count: 3,
    kudos_count: 1,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a11628851514",
      summary_polyline:
        "azj|Gmb|nCAEBB?DC@@n@Lp@Db@GpADb@?z@NvAXvAA`@@JP~@R\\HVV`@b@`BN^R\\Bb@C`@KLg@`@MFI@IDm@r@aA\\IBi@?k@MUIa@k@QMIM_@{@YWOa@i@cAK[MQcAiBe@sAMMMPKb@Od@GFSCIJI`@Kz@ALFpA?RIjBOdA@~AAl@DLFHKOAIBm@GwABg@FSBaAFs@B{@BQ?nA]nDD`BCl@Dq@IcBNoAH{BDk@AfACj@ETEn@Gb@ATDzAC|@@?CAAGBq@GwAJ}@?]Fc@J{B?dAGn@EhAIz@B~@CfA?JGuC@SN{@LgD@bAMhAAp@Kt@FxAIx@@g@GaBJy@VeE?dAWnDB|AEx@?}@Gq@?g@RgBNkC?~@Ev@IfAG\\CTBv@C~AESBi@CyAHs@DkAPsBEfBIn@Ad@In@@bBEl@A?Fy@GoAJw@R_EBr@EXAr@K`AK`@DbBCbAA[?_ACs@\\}FAjAKxBKn@DpAAf@EVBc@AsAAWFo@@}@LkAD_A?lAIhBOfABnACz@@cAGgABa@DYRmDEaA@[R_AHKTCLOD]Rs@^f@X`@xAxC`@n@v@dBTXRb@h@b@HNHJVN^Fb@AXEhBg@`@SRU@[PY?KSk@e@aAYcA[o@[yAGe@@wAIe@UaCCu@Iu@KuBGe@@e@E_@HgAPMp@KJ?XEBCAAWL",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [46.7550565302372, 23.578155152499676],
    end_latlng: [46.75468320026994, 23.57881790958345],
    average_speed: 2.055,
    max_speed: 3.794,
    average_cadence: 75.2,
    average_watts: 198.1,
    max_watts: 421,
    weighted_average_watts: 206,
    kilojoules: 524.5,
    device_watts: true,
    has_heartrate: true,
    average_heartrate: 158.7,
    max_heartrate: 175,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 462.6,
    elev_low: 409.8,
    upload_id: 12409579756,
    upload_id_str: "12409579756",
    external_id: "garmin_ping_347096594594",
    from_accepted_tag: false,
    pr_count: 1,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 113249417,
      resource_state: 1,
    },
    name: "Morning Trail Run",
    distance: 32545.8,
    moving_time: 16622,
    elapsed_time: 17346,
    total_elevation_gain: 257,
    type: "Run",
    sport_type: "TrailRun",
    workout_type: null,
    id: 11611967829,
    start_date: "2024-06-09T08:43:49Z",
    start_date_local: "2024-06-09T10:43:49Z",
    timezone: "(GMT+01:00) Europe/Berlin",
    utc_offset: 7200,
    location_city: null,
    location_state: null,
    location_country: "Romania",
    achievement_count: 0,
    kudos_count: 1,
    comment_count: 1,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a11611967829",
      summary_polyline:
        "m{wlH{~hgARqBc@KO[@aAr@gJPmDBaCNkACo@bA_OZ}@APAS@JBMV@jAi@Zg@Bs@N]xGgIzB_B|COh@IZYjCBVTb@~AnAFz@Z`Co@|C?xDt@pFxB|@|@~DjCl@?jHdHxBvAf@Pp@QFVTRnCFvDl@\\H\\b@Lj@NPvA@rChAjCXJZFtALjUXfDh@rCnVpu@rMt`@nBtDnAjApElCrBdALYBq@Q{BgAqDY_Bl@gFfDqIhDyMdJiWv@qEfBcCr@yArBiG~BgGv@mDv@wBn@u@tCoBPkAJeH@qBQiBRw@~BP`DdAHKnAXvAGlDkAbBM~CLzBt@l@|@TfA`@nPTlBb@vA`@v@t@f@z@LrVkCxDkAlJmFnEuCjAiAdGoKrDwFl@_@^m@x@WhBGbAX`BlAvBvChB`@xLkFxA_@zGr@lEPfSStGg@pBLjA}AfAYjE^|MzBbA?fCQ`Dq@hCoArBwAxL{KlEgFrBgDbFcLzByCnDkBnKyDjHcEjQoNdIyF~CsCfAwA~@mB\\wB^mEb@cBr@yAtDaE`BcCvA_D`D{KpDsTrBeIvBoLfEaWdBuLGk@mGoMaAmCcBuDHYp@o@ZaAVwEr@aE@c@KSKR@[\\A~BaMlAoJvAwIHkGi@gIFuAE}Ai@{KWeCKqDJgC?yDKcJj@{Qb@wENeGJAV}Dj@oDLcCEu@oA}Iu@oKOkDgFc@uDBsGdCkI|DwBtBuFvIeLzJ}F|FeN~PoBtAuK~FuDhDqCbBwATaBC}Ag@qA{@uKmI_IwKsC_CaDu@oCP{Al@wA~@qBnCmBfGq@~DsB|NOlBsAhIu@vCsAxDuAxC}AtBoBrAmDbAiCDoZiHiB@kHv@wBf@wD`Bwf@pWcFz@_BPBKcR`De@KqRr@mH~ByBvAuAlB_G`KwAzA}H~FgBnBqC|DUKHVKXiBvC_DlH}BxH}ExSgGlg@qCnMkApE{@rBk@p@eB`BwHrFYDkArAq@\\e@\\eAbAuGzEoGfBcB|@eCh@yOnMcElCi@n@eCdBkBl@iDPwAh@kAFoFzAsAl@wA|Bu@h@mBEgB~@u@Wz@RbB{@nAFp@Sh@m@dBuCEiBiAg@}AyAcAzA{AzCk@TgA@aAa@aBoByAeCk@_@MDg@fAB`AKd@DfAeGfFwEtIi@xCJzFE~@sC~@y@|@eApBWjBuAdBy@fBa@lAO`BSn@{DdFw@l@s@?_@[YCGrF?\\FBIt@[x@q@bHe@tIQfJs@lHC`DF`@ZLM]",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [49.443270759657025, 11.847665822133422],
    end_latlng: [49.44306037388742, 11.848040074110031],
    average_speed: 1.958,
    max_speed: 3.893,
    average_cadence: 81.5,
    average_temp: 29,
    average_watts: 185.9,
    max_watts: 307,
    weighted_average_watts: 192,
    kilojoules: 3089.3,
    device_watts: true,
    has_heartrate: true,
    average_heartrate: 151,
    max_heartrate: 171,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 502.8,
    elev_low: 372.4,
    upload_id: 12392197456,
    upload_id_str: "12392197456",
    external_id: "garmin_ping_346573588900",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 113249417,
      resource_state: 1,
    },
    name: "Afternoon Run",
    distance: 12460.1,
    moving_time: 5942,
    elapsed_time: 5944,
    total_elevation_gain: 76,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 11540299622,
    start_date: "2024-05-31T12:35:38Z",
    start_date_local: "2024-05-31T14:35:38Z",
    timezone: "(GMT+01:00) Europe/Berlin",
    utc_offset: 7200,
    location_city: null,
    location_state: null,
    location_country: "Romania",
    achievement_count: 0,
    kudos_count: 1,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a11540299622",
      summary_polyline:
        "{nimHs~_gA?IKo@Gw@o@uAKk@Cc@BS^W`A_AR?Fa@rAmCfBeCr@s@j@[t@QR@zAa@jC}@v@]RU`@[`@LAOIQ?Or@}@\\s@r@sBh@_C@MCKAKFi@@u@Hu@^_LAaBD[Ta@h@Tz@L`CLnANpBAdAFrAEnCOx@IhE}@dFuAzBaAX?nAQl@g@r@[jAQhAa@zA[~Di@v@?`BMdCHd@EbAF`FD~APp@@~CQ|@WrCa@pA_@xCmAfA]bCsAtAg@zBkAhBmApAgBjA_Aj@]jAe@lAUlC}AhCeBp@_@jD{BxBeBJMbAw@D?XUf@WZ_@Zu@NMn@Sv@e@^GD??B@GJGIN?RDDFd@Fj@CzED~@BF?^HnABt@DPJFdAc@rAOxFEbAE`AM~Bg@vAk@`AWz@k@~@OXH`@\\lDvETLd@@^UtDgF^Y\\@x@|@n@Tb@Ed@Qf@]v@_@n@SXAnBPb@LJE^Dr@TPAb@MHIDORgCBu@Ls@FU\\m@Za@`@Af@Kh@Vx@D|A`@j@AJE\\PNZDZInAHzBh@vATb@D@JZDj@FJD@lCsE^c@VKVUP[tAqBtAuAvAgAz@}@lAeA`@YlAsAHCz@q@vBoBV]h@a@hDyExD}G`A_BTk@Ze@x@aBb@a@x@Op@[XHHAZi@RQrA[dEANGn@@|AMzAB~BMvA@x@EtA]tCgAx@_@`B]^Fl@Ez@FHHP\\RA`@w@fCeDf@i@`@o@DGG[?OLa@h@a@jAgB|AqBdA_BzC}Dv@mA`CgDd@q@Te@t@eAlBaCzAcBRY`H_Ij@w@p@u@xAkB\\]j@u@\\Y^a@~@oAt@o@^c@NYnAaBxA{AhB}AfCsAZGn@W|@QdA]jAIjAUlBEbD[dAW\\Wr@q@n@u@|@oBFe@Pm@L{@B_@@w@Hs@J}ARUb@kCZaAl@{Al@iA^c@z@{@tAcAz@]|@Wx@a@r@QNIAi@B[DWHGxEiAt@JhGkBn@I`Du@j@Eb@\\PBj@KFGP@XPFZp@dDJr@Bj@R\\FRRrAJXRnALRZLh@l@P@h@Pn@\\HFHVJHz@TjARl@d@r@VJNDACARAh@JbBEpADNNRBHFBF?t@VFA@@FNAC@",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [49.53342357650399, 11.801548087969422],
    end_latlng: [49.442973118275404, 11.847881404682994],
    average_speed: 2.097,
    max_speed: 5.046,
    average_cadence: 83,
    average_watts: 195.6,
    max_watts: 299,
    weighted_average_watts: 201,
    kilojoules: 1162,
    device_watts: true,
    has_heartrate: true,
    average_heartrate: 149.8,
    max_heartrate: 176,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 405.2,
    elev_low: 376.8,
    upload_id: 12318437264,
    upload_id_str: "12318437264",
    external_id: "garmin_ping_344432558263",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 113249417,
      resource_state: 1,
    },
    name: "Afternoon Run",
    distance: 5113.6,
    moving_time: 2620,
    elapsed_time: 2702,
    total_elevation_gain: 38,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 11526557066,
    start_date: "2024-05-29T15:21:20Z",
    start_date_local: "2024-05-29T17:21:20Z",
    timezone: "(GMT+01:00) Europe/Berlin",
    utc_offset: 7200,
    location_city: null,
    location_state: null,
    location_country: "Romania",
    achievement_count: 0,
    kudos_count: 1,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a11526557066",
      summary_polyline:
        "{limHcw_gAAXHl@HRLt@Vp@Jj@@b@Nx@Ap@k@hAQVYVi@\\qAj@GFMRI`@[|@_@l@Sj@Y`@[x@_@|AOlAId@Od@EZEdC?p@HnB?l@YnBSdAEtBDjBL~B@xADDBV@ZRnBBdBH^JbB@pAC`AGv@Gh@YhAGf@i@rLGdCCPGBe@Du@LQJSZi@bBSx@IBa@Ck@HUHK@KIIQa@kCe@mCOg@cAcGWmAWgBQwBSqG@u@_@yIA}AEMEICAK?}CfBc@\\e@TQRo@Zi@b@iAr@MJ{BxAEFEX?fGC~@@hHEzA@|D?nDCdAFf@`@zAN`@b@fB{@wD[_AE_@DgCAiA@gFFu@CaB@mB@{LPWNIROLCf@_@b@WVU~@i@NYNKjBgAPObAm@r@g@`@WLEDGjBe@x@KpAWNAxA_@d@Eb@I`AURSHUJi@D_A@WEiA@sBDsBDq@?u@Dw@JOz@Kn@QTQNWNe@b@cDJc@Vq@^u@HWHIJ]~@yBV_@HEr@]TEXURK`@_@n@iADa@A[Oq@Ge@I[",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [49.53310917131603, 11.800339920446277],
    end_latlng: [49.53286651521921, 11.799203753471375],
    average_speed: 1.952,
    max_speed: 2.802,
    average_cadence: 81.7,
    average_watts: 183.3,
    max_watts: 252,
    weighted_average_watts: 182,
    kilojoules: 480.4,
    device_watts: true,
    has_heartrate: true,
    average_heartrate: 132.6,
    max_heartrate: 146,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 408.4,
    elev_low: 382,
    upload_id: 12304292901,
    upload_id_str: "12304292901",
    external_id: "garmin_ping_344005416925",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 113249417,
      resource_state: 1,
    },
    name: "Evening Football (Soccer)",
    distance: 4142.9,
    moving_time: 3204,
    elapsed_time: 3371,
    total_elevation_gain: 0,
    type: "Soccer",
    sport_type: "Soccer",
    id: 11414714215,
    start_date: "2024-05-14T17:04:11Z",
    start_date_local: "2024-05-14T20:04:11Z",
    timezone: "(GMT+02:00) Europe/Bucharest",
    utc_offset: 10800,
    location_city: null,
    location_state: null,
    location_country: "Romania",
    achievement_count: 0,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a11414714215",
      summary_polyline:
        "_xm|GcdgoCCBDLI@BAAC?D]ZCCCSHA?GHn@BGEKBAE@DCBKBLBIDBCDGKDGK?FEFJN?APGEBADIEMANFFLI@GUD@K@HLIIB?DSN?IOB?DEGFBCc@C?EJHPA?JLMC@CLSE@@?EFh@w@EG@NGP?NSFBJJABDQBCKFH@IEADC?QDDTI?FCFEa@SZ@JCECPEDJEXi@GBEC@ADABFJBGHEGGB?DNEBFAHCE?G?FGGGPML@DIIXEMD?OHDBCQ@DHNEDMCMFEOP?HGFC@MSIT?HDGCQKFBEJDLe@R?I?@MBJEVBFGJECEB@QMDFHDICDB@JO@@AAELB@GNLEFI[DV?TS?BGCe@XD?EHEE?FBH@KEEJGO?BQDALXNC?QEFFa@@D[d@AFD?CQ@GRa@?N?EEDEEZd@EOM?FGD@AIILAKI@?DKH@B\\BFHEGIDFQKBNc@YTCJIIFNEEEFF[GP@DBID?B[OA?DH@M^EEH?AKA??ZBBLI?C?DWHDHF@AENc@GH@D@EOACFDNDIZGFG@ICSEBAJFLU?HTCIC?FKI?CHB?EANi@LBQNGJ?JK@GN@FLGCDDYGCMFFXNIIA?K\\[@GAHI?EABCC@ETXQF@?HS?CFOB?TEAHGCEARAMEBDC@DA??EEC@EEBFAAEEDDKDPAGNGMBKLA^BCAEDO?MJBGAAEC@NMILIAHTDGE@TGUACDF@d@UUAGHJMH]CIIGCDBBN?@TAF]VWECGADBB?GRHDA?H?CLA@EE?MBEHPg@APGCH@?`@D?K?CGH[DFADEAADAGKHB?De@RYET@BEAANKNAAD@CFH@CGE@BE@@EJDQL@E?@FS@KQADFIFDA@B?E?B??DM\\@BV[EA?DBC?DG@LJIOPQMFLCKL@BNg@SJLFEOCBV?Ib@EEBKMHCJBAM?HSMDNGHBGYICEFAVRKJFCHSHELL[I?MH?C\\BTO@EAIOVKDAEWAVI@IAHK?KDFDHIKJPM?CCDG[Cb@JIPc@CF@NCTINFAEALK?OKXH?EGAMABRLBKKGID?HEFXi@?NQPCGGVL[AGAJ?ID@BJCECFKHJ[GPHDCLKCABF[HC?F?GAHBEGCCH@BNBNAPQ_@FYVHOj@[[T?FHCDOE??GEPE@?u@@DS^B??HHEHMBa@ECHN?DKRC@CLAUIEFEBJALGEEDFCLWCGABMb@DFKJRMRQq@`@@@^g@@DBCGPMHR@OEKTBH@[BC",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [46.77008494734764, 23.634741129353642],
    end_latlng: [46.77014781162143, 23.634627303108573],
    average_speed: 1.293,
    max_speed: 5.544,
    average_cadence: 68.1,
    has_heartrate: true,
    average_heartrate: 144.7,
    max_heartrate: 186,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 332,
    elev_low: 329.6,
    upload_id: 12189027632,
    upload_id_str: "12189027632",
    external_id: "garmin_ping_340628208643",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: {
      id: 113249417,
      resource_state: 1,
    },
    name: "Afternoon Football (Soccer)",
    distance: 5337.2,
    moving_time: 4043,
    elapsed_time: 4143,
    total_elevation_gain: 0,
    type: "Soccer",
    sport_type: "Soccer",
    id: 10663044748,
    start_date: "2024-01-28T12:58:44Z",
    start_date_local: "2024-01-28T14:58:44Z",
    timezone: "(GMT+02:00) Europe/Bucharest",
    utc_offset: 7200,
    location_city: null,
    location_state: null,
    location_country: "Romania",
    achievement_count: 0,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a10663044748",
      summary_polyline:
        "avm|Ge`goCGDDF?M@JKBREIFBEEEDDAFCIFDCCBAGDCKHs@G^AMILCABCEB?G@F@GCHFJHEBNC@@DE?B?Gg@KCDNIDNBU??JEBBDJKOBAMFXNQENG?BBGPEERK@KOMINBFD@L[NJGHBB?IWTHQEEh@H@UUHDMMPKBDBEFAMFM]DADNDDIC@VQIMC@JNVKMK@Je@d@P?VQCFK@EYJ[JAGXCGCHIOL?EXUDE^JEC]OV?ODJB?BMKDCGNLAMOH@IHRJAYPf@c@AINB@IWTH?IHDAQATUKDGTOIN?GJFHNKNa@WXPREUH@?E?H@]B@I?AS@I@R?WMd@?JDFUIPRKDJQMf@BINIGFAQKIKHHGEIJ@ETHEOPRYG@TOFUG?SV@BAEBJMMANJNESKCE\\^[BICINKe@f@AJEBBS@BCD?QFD@LK?ROF@CHXe@a@RI?DSB?@RD@FOEJBPCDOGOODBCFNM@HGA@JJCGJGQL@EFHOCFSDDZAMD@OKDODHFCN[BHI@T[ENE?@LI@DHAQQ?FNIJFDE@EJBQHEN?@RCOMCBFDOTQCAKHE^a@?VMIEKLBHXQ@DECCRMBNUDBCCEJ@NCGJOIICBAPBQFRCKEHNCRYIQKJ?LMADHP]KXDEPY@OGPFKBD]b@@MCJBAGI@LNW?FDBg@h@R[JCIF[CZ@IQC\\?IHACFAMO@DD@IMETKG\\BU@JPAAQUZDF@WBTCUAFKDF@DINVTWCFKGGXJOSFTMBI?IKKRHDNIO_@b@GUF?@WI`@?QLDKLGKL@GJHCKFBMGMFKL?FFQFVOADKAAKVK?G[r@@LFC?FLKJWKBAIHCDNEBKg@B?CDk@fAH?BJLSBQOPIEFGCMJK?^?MCJOGDAAFBFBGEHp@WCIWNDEAWA\\CAR??OPPF?WAGLTACAIi@CDDF_@RDLWG?HB@LU@@Q?EJJ@r@UMAIPBECECJQBCHj@_@EDBBICIFNK@GIAKZO?HOEDBRO?FFVGUHLO[Fb@MNMECAJIBSA^?LQOLAPJKILUII@BEJJGKC??HGATQMRWEXS?VEFIUH?HNXWL@HDUASNQ@T]PI?_@BLUh@ATYD?M@FPDB_@K@CDDGPH_@LB^PQCKE?HIUDF?EJB@JI@IIANBEIF?OP?DHDBEMBGJPEF[@QMG?VI??FFEADB??IDAE?ENG@XS[TR]LDUDCDGLH@AN?GIGD?ADBGEEJ?BX[Qn@[XUG@H@SOAIHMo@}Bk@{AKU]JG[",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [46.7697727214545, 23.634113911539316],
    end_latlng: [46.77045609802008, 23.635642183944583],
    average_speed: 1.32,
    max_speed: 6.012,
    average_cadence: 63,
    has_heartrate: true,
    average_heartrate: 146,
    max_heartrate: 181,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 332.4,
    elev_low: 330.4,
    upload_id: 11405166055,
    upload_id_str: "11405166055",
    external_id: "garmin_ping_318293973068",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
];
